window.EVOL_EARTH_HISTORY = {
  oldestMa: 4500,
  youngestMa: 0.01,
  ticks: [
    { ma: 4000, ru: "4 млрд", en: "4 bn" },
    { ma: 1000, ru: "1 млрд", en: "1 bn" },
    { ma: 100, ru: "100 млн", en: "100 m" },
    { ma: 10, ru: "10 млн", en: "10 m" },
    { ma: 1, ru: "1 млн", en: "1 m" },
    { ma: 0.1, ru: "100 тыс.", en: "100 k" },
    { ma: 0.01, ru: "10 тыс.", en: "10 k" },
  ],
  transitions: [
    { ma: 252, short: { ru: "P–Tr", en: "P–Tr" }, label: { ru: "Пермское массовое вымирание", en: "Permian mass extinction" } },
    { ma: 66, short: { ru: "K–Pg", en: "K–Pg" }, label: { ru: "Астероид и массовое вымирание K–Pg", en: "Asteroid impact and K–Pg mass extinction" } },
  ],
  snapshots: [
    {
      fromMa: 4500,
      toMa: 3800,
      title: { ru: "Молодая Земля", en: "Young Earth" },
      period: { ru: "хадей", en: "Hadean" },
      headline: { ru: "Планета остывает, появляются кора и океаны", en: "The planet cools; crust and oceans form" },
      atmosphere: { ru: "Почти нет свободного кислорода. Вулканические газы, азот, углекислый газ и водяной пар.", en: "Almost no free oxygen. Volcanic gases, nitrogen, carbon dioxide, and water vapor." },
      land: { ru: "Горячие голые породы, вулканы и частые удары космических тел.", en: "Hot bare rock, volcanoes, and frequent impacts." },
      sea: { ru: "Первые устойчивые океаны; подтвержденной жизни пока нет.", en: "The first stable oceans; no confirmed life yet." },
      landLife: [],
      seaLife: [],
      airLife: [],
      colors: ["#a6a19a", "#6c5142", "#416d79"],
    },
    {
      fromMa: 3800,
      toMa: 2400,
      title: { ru: "Мир микробов", en: "Microbial world" },
      period: { ru: "архей", en: "Archean" },
      headline: { ru: "Жизнь существует только в воде и микробных пленках", en: "Life exists only in water and microbial mats" },
      atmosphere: { ru: "Кислорода почти нет; Солнце слабее современного, но парниковые газы удерживают тепло.", en: "Almost no oxygen; the Sun is dimmer, while greenhouse gases retain heat." },
      land: { ru: "Безжизненные каменные острова и молодые континенты.", en: "Lifeless rocky islands and young continents." },
      sea: { ru: "Бактерии и археи осваивают разные химические источники энергии.", en: "Bacteria and archaea exploit many chemical energy sources." },
      landLife: [],
      seaLife: [
        { marker: "microbe", label: { ru: "бактерии и археи", en: "bacteria and archaea" }, status: "dominant" },
        { marker: "algae", label: { ru: "микробные маты", en: "microbial mats" }, status: "common" },
      ],
      airLife: [],
      colors: ["#b7a76e", "#78694b", "#386f75"],
    },
    {
      fromMa: 2400,
      toMa: 1800,
      title: { ru: "Кислородная революция", en: "Oxygen revolution" },
      period: { ru: "палеопротерозой", en: "Paleoproterozoic" },
      headline: { ru: "Фотосинтез меняет океан, воздух и минералы планеты", en: "Photosynthesis transforms oceans, air, and minerals" },
      atmosphere: { ru: "Кислород впервые заметно накапливается; метана становится меньше.", en: "Oxygen accumulates noticeably for the first time; methane declines." },
      land: { ru: "Суша еще пуста, но железо и другие минералы окисляются.", en: "Land remains empty, while iron and other minerals oxidize." },
      sea: { ru: "Цианобактерии выделяют кислород; многие анаэробные микробы отступают в бескислородные среды.", en: "Cyanobacteria release oxygen; many anaerobes retreat to oxygen-free environments." },
      landLife: [],
      seaLife: [
        { marker: "chloroplast", label: { ru: "цианобактерии", en: "cyanobacteria" }, status: "dominant" },
        { marker: "microbe", label: { ru: "анаэробные микробы", en: "anaerobic microbes" }, status: "common" },
      ],
      airLife: [],
      colors: ["#9eb8b7", "#806b52", "#397985"],
    },
    {
      fromMa: 1800,
      toMa: 800,
      title: { ru: "Сложная клетка", en: "Complex cells" },
      period: { ru: "протерозой", en: "Proterozoic" },
      headline: { ru: "Эукариоты приносят ядро, органеллы и половое размножение", en: "Eukaryotes bring nuclei, organelles, and sexual reproduction" },
      atmosphere: { ru: "Кислорода больше, чем в архее, но заметно меньше современного уровня.", en: "More oxygen than in the Archean, but far below modern levels." },
      land: { ru: "Континенты пусты; жизнь сосредоточена в воде и на влажных поверхностях.", en: "Continents are empty; life is concentrated in water and on wet surfaces." },
      sea: { ru: "Наряду с прокариотами распространяются клетки с ядром и водоросли.", en: "Nucleated cells and algae spread alongside prokaryotes." },
      landLife: [],
      seaLife: [
        { marker: "microbe", label: { ru: "прокариоты", en: "prokaryotes" }, status: "dominant" },
        { marker: "nucleus", label: { ru: "эукариоты", en: "eukaryotes" }, status: "new" },
        { marker: "algae", label: { ru: "водоросли", en: "algae" }, status: "common" },
      ],
      airLife: [],
      colors: ["#a9c2bf", "#79705b", "#397f8c"],
    },
    {
      fromMa: 800,
      toMa: 541,
      title: { ru: "Многоклеточный мир", en: "Multicellular world" },
      period: { ru: "неопротерозой", en: "Neoproterozoic" },
      headline: { ru: "Появляются крупные многоклеточные организмы", en: "Large multicellular organisms appear" },
      atmosphere: { ru: "Кислород приближается к уровню, достаточному для крупных активных тел.", en: "Oxygen approaches levels sufficient for large active bodies." },
      land: { ru: "Суша почти безжизненна; возможны микробные пленки и простые грибы у воды.", en: "Land is nearly lifeless, with possible microbial films and simple fungi near water." },
      sea: { ru: "Водоросли, ранние животные и мягкотелые эдиакарские сообщества.", en: "Algae, early animals, and soft-bodied Ediacaran communities." },
      landLife: [{ marker: "fungus", label: { ru: "простые наземные формы", en: "simple terrestrial forms" }, status: "new" }],
      seaLife: [
        { marker: "algae", label: { ru: "многоклеточные водоросли", en: "multicellular algae" }, status: "common" },
        { marker: "animal", label: { ru: "ранние животные", en: "early animals" }, status: "new" },
        { marker: "bilateral", label: { ru: "билатерии", en: "bilaterians" }, status: "new" },
      ],
      airLife: [],
      colors: ["#a8bdc1", "#80745f", "#487f91"],
    },
    {
      fromMa: 541,
      toMa: 470,
      title: { ru: "Жизнь заполняет моря", en: "Life fills the seas" },
      period: { ru: "кембрий — ордовик", en: "Cambrian–Ordovician" },
      headline: { ru: "Скелеты, глаза, хищники и множество планов тела", en: "Skeletons, eyes, predators, and many body plans" },
      atmosphere: { ru: "Кислорода достаточно для активных животных; озоновый слой усиливается.", en: "Enough oxygen for active animals; the ozone layer strengthens." },
      land: { ru: "Материки остаются почти полностью безжизненными; настоящей почвы еще нет.", en: "Continents remain almost entirely lifeless; true soil has not yet formed." },
      sea: { ru: "Главное разнообразие жизни находится в море.", en: "Most of life's diversity is in the sea." },
      landLife: [],
      seaLife: [
        { marker: "bilateral", label: { ru: "беспозвоночные", en: "invertebrates" }, status: "dominant" },
        { marker: "chord", label: { ru: "хордовые", en: "chordates" }, status: "new" },
        { marker: "fin", label: { ru: "ранние рыбы", en: "early fish" }, status: "common" },
      ],
      airLife: [],
      colors: ["#91b9c3", "#8a7d61", "#367e9a"],
    },
    {
      fromMa: 470,
      toMa: 420,
      title: { ru: "Первые зеленые берега", en: "The first green shores" },
      period: { ru: "ордовик — силур", en: "Ordovician–Silurian" },
      headline: { ru: "Растения и грибы начинают осваивать влажную сушу", en: "Plants and fungi begin colonizing damp land" },
      atmosphere: { ru: "Озоновый слой защищает поверхность; кислорода постепенно становится больше.", en: "The ozone layer shields the surface as oxygen gradually increases." },
      land: { ru: "Низкие простые растения, грибы и первые тонкие почвы появляются у воды.", en: "Low simple plants, fungi, and the first thin soils appear near water." },
      sea: { ru: "Морские беспозвоночные очень разнообразны; рыбы начинают заметно расходиться на ветви.", en: "Marine invertebrates are highly diverse; fish begin splitting into visible lineages." },
      landLife: [
        { marker: "leaf", label: { ru: "первые наземные растения", en: "first land plants" }, status: "new" },
        { marker: "fungus", label: { ru: "грибы", en: "fungi" }, status: "new" },
      ],
      seaLife: [
        { marker: "bilateral", label: { ru: "морские беспозвоночные", en: "marine invertebrates" }, status: "dominant" },
        { marker: "fin", label: { ru: "ранние рыбы", en: "early fish" }, status: "common" },
      ],
      airLife: [],
      colors: ["#96bbc0", "#778064", "#397f98"],
    },
    {
      fromMa: 420,
      toMa: 360,
      title: { ru: "Выход на сушу", en: "Life moves onto land" },
      period: { ru: "силур — девон", en: "Silurian–Devonian" },
      headline: { ru: "Растения и членистоногие создают наземные сообщества", en: "Plants and arthropods build terrestrial communities" },
      atmosphere: { ru: "Кислород растет, климат в основном теплый.", en: "Oxygen rises; climate is mostly warm." },
      land: { ru: "Сосудистые растения, первые леса, грибы и наземные членистоногие.", en: "Vascular plants, first forests, fungi, and terrestrial arthropods." },
      sea: { ru: "Разнообразятся челюстные и костные рыбы.", en: "Jawed and bony fish diversify." },
      landLife: [
        { marker: "vascular", label: { ru: "сосудистые растения", en: "vascular plants" }, status: "dominant" },
        { marker: "fungus", label: { ru: "грибы", en: "fungi" }, status: "common" },
        { marker: "limb", label: { ru: "наземные членистоногие", en: "land arthropods" }, status: "common" },
      ],
      seaLife: [
        { marker: "jaw", label: { ru: "челюстные рыбы", en: "jawed fish" }, status: "dominant" },
        { marker: "fin", label: { ru: "лопастеперые", en: "lobe-finned fish" }, status: "new" },
      ],
      airLife: [],
      colors: ["#8db9ba", "#68804d", "#397c96"],
    },
    {
      fromMa: 360,
      toMa: 252,
      title: { ru: "Леса и четвероногие", en: "Forests and tetrapods" },
      period: { ru: "карбон — пермь", en: "Carboniferous–Permian" },
      headline: { ru: "Леса меняют воздух, а позвоночные осваивают сушу", en: "Forests alter the air as vertebrates colonize land" },
      atmosphere: { ru: "В карбоне кислорода особенно много; к концу перми климат становится суше.", en: "Oxygen is especially high in the Carboniferous; climate dries toward the Permian." },
      land: { ru: "Обширные леса, крупные членистоногие, земноводные и первые амниоты.", en: "Vast forests, large arthropods, amphibians, and early amniotes." },
      sea: { ru: "Рыбы остаются разнообразными; развиты рифы и морские беспозвоночные.", en: "Fish remain diverse; reefs and marine invertebrates flourish." },
      landLife: [
        { marker: "fern", label: { ru: "болотные леса", en: "swamp forests" }, status: "dominant" },
        { marker: "limb", label: { ru: "земноводная линия", en: "amphibian lineage" }, status: "common" },
        { marker: "egg", label: { ru: "амниоты", en: "amniotes" }, status: "new" },
        { marker: "split", label: { ru: "синапсиды и завропсиды", en: "synapsids and sauropsids" }, status: "new" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "костные рыбы", en: "bony fish" }, status: "dominant" },
        { marker: "bilateral", label: { ru: "морские беспозвоночные", en: "marine invertebrates" }, status: "common" },
      ],
      airLife: [],
      colors: ["#9fc2b5", "#426c43", "#3f7d91"],
    },
    {
      fromMa: 252,
      toMa: 201,
      title: { ru: "Восстановление после катастрофы", en: "Recovery after catastrophe" },
      period: { ru: "триас", en: "Triassic" },
      headline: { ru: "Архозавры, первые динозавры и млекопитающие занимают новый мир", en: "Archosaurs, early dinosaurs, and mammals enter a new world" },
      transition: {
        label: { ru: "~252 млн: пермское массовое вымирание", en: "~252 Ma: Permian mass extinction" },
        effect: { ru: "Исчезло большинство морских видов; наземные экосистемы пришлось собирать заново.", en: "Most marine species vanished, and terrestrial ecosystems had to rebuild." },
      },
      atmosphere: { ru: "Теплый парниковый мир; полярных ледников почти нет.", en: "A warm greenhouse world with little polar ice." },
      land: { ru: "После пермского вымирания экосистемы восстанавливаются; расходятся две линии архозавров.", en: "Ecosystems recover after the Permian extinction; the two archosaur lineages diverge." },
      sea: { ru: "Аммониты, костные рыбы и крупные морские рептилии.", en: "Ammonites, bony fish, and large marine reptiles." },
      landLife: [
        { marker: "seed", label: { ru: "голосеменные", en: "gymnosperms" }, status: "common" },
        { marker: "dino", label: { ru: "ранние динозавры", en: "early dinosaurs" }, status: "new" },
        { marker: "jaw", label: { ru: "крокодилья линия", en: "crocodilian lineage" }, status: "common" },
        { marker: "mammal", label: { ru: "ранние млекопитающие", en: "early mammals" }, status: "new" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "костные рыбы", en: "bony fish" }, status: "common" },
        { marker: "animal", label: { ru: "морские рептилии", en: "marine reptiles" }, status: "common" },
      ],
      airLife: [{ marker: "bird", label: { ru: "птерозавры", en: "pterosaurs" }, status: "new" }],
      colors: ["#b7c8aa", "#657348", "#497d8d"],
    },
    {
      fromMa: 201,
      toMa: 145,
      title: { ru: "Юрский мир", en: "Jurassic world" },
      period: { ru: "юра", en: "Jurassic" },
      headline: { ru: "Динозавры господствуют на суше, появляются первые птицы", en: "Dinosaurs dominate land as the first birds appear" },
      atmosphere: { ru: "Теплый влажный климат без постоянных полярных ледников.", en: "Warm, humid climate without permanent polar ice." },
      land: { ru: "Голосеменные леса кормят крупных динозавров; рядом живут небольшие млекопитающие.", en: "Gymnosperm forests feed large dinosaurs; small mammals live alongside them." },
      sea: { ru: "Много костных рыб, аммонитов и крупных морских рептилий.", en: "Bony fish, ammonites, and large marine reptiles are abundant." },
      landLife: [
        { marker: "seed", label: { ru: "голосеменные", en: "gymnosperms" }, status: "dominant" },
        { marker: "dino", label: { ru: "динозавры", en: "dinosaurs" }, status: "dominant" },
        { marker: "jaw", label: { ru: "крокодилья линия", en: "crocodilian lineage" }, status: "common" },
        { marker: "mammal", label: { ru: "ранние млекопитающие", en: "early mammals" }, status: "common" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "костные рыбы", en: "bony fish" }, status: "common" },
        { marker: "animal", label: { ru: "морские рептилии", en: "marine reptiles" }, status: "dominant" },
      ],
      airLife: [
        { marker: "bird", label: { ru: "птерозавры", en: "pterosaurs" }, status: "common" },
        { marker: "bird", label: { ru: "ранние птицы", en: "early birds" }, status: "new" },
      ],
      colors: ["#b7cba9", "#5f7848", "#477f91"],
    },
    {
      fromMa: 145,
      toMa: 66,
      title: { ru: "Цветы и динозавры", en: "Flowers and dinosaurs" },
      period: { ru: "мел", en: "Cretaceous" },
      headline: { ru: "Цветковые и насекомые перестраивают наземные экосистемы", en: "Flowering plants and insects reshape land ecosystems" },
      atmosphere: { ru: "Теплый климат и высокий уровень моря; к концу периода начинается похолодание.", en: "Warm climate and high seas; cooling begins near the end." },
      land: { ru: "Цветковые распространяются рядом с хвойными; динозавры остаются крупнейшими животными.", en: "Flowering plants spread alongside conifers; dinosaurs remain the largest animals." },
      sea: { ru: "Костные рыбы становятся разнообразнее; живут крупные морские рептилии и моллюски.", en: "Bony fish diversify alongside large marine reptiles and mollusks." },
      landLife: [
        { marker: "flower", label: { ru: "цветковые", en: "flowering plants" }, status: "new" },
        { marker: "dino", label: { ru: "динозавры", en: "dinosaurs" }, status: "dominant" },
        { marker: "mammal", label: { ru: "млекопитающие", en: "mammals" }, status: "common" },
        { marker: "animal", label: { ru: "насекомые", en: "insects" }, status: "common" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "костные рыбы", en: "bony fish" }, status: "dominant" },
        { marker: "animal", label: { ru: "морские рептилии", en: "marine reptiles" }, status: "common" },
      ],
      airLife: [
        { marker: "bird", label: { ru: "птерозавры", en: "pterosaurs" }, status: "common" },
        { marker: "bird", label: { ru: "птицы", en: "birds" }, status: "common" },
      ],
      colors: ["#b9d0aa", "#66854a", "#4a8292"],
    },
    {
      fromMa: 66,
      toMa: 23,
      title: { ru: "Мир после астероида", en: "World after the asteroid" },
      period: { ru: "палеоген", en: "Paleogene" },
      headline: { ru: "Млекопитающие и птицы быстро занимают освободившиеся роли", en: "Mammals and birds rapidly fill newly open roles" },
      transition: {
        label: { ru: "~66 млн: астероид и вымирание K–Pg", en: "~66 Ma: asteroid impact and K–Pg extinction" },
        effect: { ru: "Нептичьи динозавры и многие морские группы исчезли; выжившие линии начали новую радиацию.", en: "Non-avian dinosaurs and many marine groups vanished; surviving lineages began a new radiation." },
      },
      atmosphere: { ru: "После резкого кризиса климат становится теплым, а затем постепенно охлаждается.", en: "After an abrupt crisis, climate becomes warm and then gradually cools." },
      land: { ru: "Леса восстанавливаются; быстро разнообразятся млекопитающие, птицы и цветковые.", en: "Forests recover while mammals, birds, and flowering plants diversify rapidly." },
      sea: { ru: "Костные рыбы и моллюски восстанавливаются; появляются ранние киты.", en: "Bony fish and mollusks recover; early whales appear." },
      landLife: [
        { marker: "flower", label: { ru: "цветковые", en: "flowering plants" }, status: "dominant" },
        { marker: "mammal", label: { ru: "млекопитающие", en: "mammals" }, status: "common" },
        { marker: "ape", label: { ru: "ранние приматы", en: "early primates" }, status: "new" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "современные линии рыб", en: "modern fish lineages" }, status: "dominant" },
        { marker: "mammal", label: { ru: "ранние киты", en: "early whales" }, status: "new" },
      ],
      airLife: [
        { marker: "bird", label: { ru: "современные птицы", en: "modern birds" }, status: "dominant" },
        { marker: "mammal", label: { ru: "летучие мыши", en: "bats" }, status: "new" },
      ],
      colors: ["#b8d3cf", "#69844f", "#4e879a"],
    },
    {
      fromMa: 23,
      toMa: 2.6,
      title: { ru: "Степи и современные группы", en: "Grasslands and modern groups" },
      period: { ru: "неоген", en: "Neogene" },
      headline: { ru: "Злаки расширяют открытые пространства, возникают знакомые сообщества", en: "Grasses expand open habitats and familiar communities emerge" },
      atmosphere: { ru: "Климат становится прохладнее и суше; полярные ледники растут.", en: "Climate becomes cooler and drier as polar ice expands." },
      land: { ru: "Расширяются степи; распространяются современные копытные, хищники и человекообразные.", en: "Grasslands expand; modern hoofed mammals, carnivores, and apes spread." },
      sea: { ru: "Киты, тюлени, морские птицы и современные рыбы образуют знакомые экосистемы.", en: "Whales, seals, seabirds, and modern fish form familiar ecosystems." },
      landLife: [
        { marker: "grass", label: { ru: "злаки", en: "grasses" }, status: "dominant" },
        { marker: "mammal", label: { ru: "современные группы млекопитающих", en: "modern mammal groups" }, status: "dominant" },
        { marker: "ape", label: { ru: "человекообразные", en: "apes" }, status: "new" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "современные рыбы", en: "modern fish" }, status: "dominant" },
        { marker: "mammal", label: { ru: "киты и тюлени", en: "whales and seals" }, status: "common" },
      ],
      airLife: [
        { marker: "bird", label: { ru: "птицы", en: "birds" }, status: "dominant" },
        { marker: "mammal", label: { ru: "летучие мыши", en: "bats" }, status: "common" },
      ],
      colors: ["#bfd2cc", "#82905a", "#51899a"],
    },
    {
      fromMa: 2.6,
      toMa: 0.3,
      title: { ru: "Ледниковые циклы", en: "Ice-age cycles" },
      period: { ru: "ранний четвертичный период", en: "Early Quaternary" },
      headline: { ru: "Ледники наступают и отступают, а человеческая линия осваивает новые земли", en: "Ice sheets advance and retreat as the human lineage enters new lands" },
      atmosphere: { ru: "Холодные и теплые интервалы многократно сменяют друг друга.", en: "Cold and warm intervals alternate repeatedly." },
      land: { ru: "Тундры, степи и леса двигаются вслед за климатом; рядом живут мегафауна и ранние люди.", en: "Tundra, grasslands, and forests shift with climate; megafauna and early humans coexist." },
      sea: { ru: "Уровень моря падает во время оледенений и поднимается в теплые интервалы.", en: "Sea level falls during glaciations and rises in warm intervals." },
      landLife: [
        { marker: "grass", label: { ru: "современные природные зоны", en: "modern biomes" }, status: "common" },
        { marker: "mammal", label: { ru: "мегафауна", en: "megafauna" }, status: "dominant" },
        { marker: "human", label: { ru: "ранние люди", en: "early humans" }, status: "new" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "современные морские экосистемы", en: "modern marine ecosystems" }, status: "common" },
        { marker: "mammal", label: { ru: "морские млекопитающие", en: "marine mammals" }, status: "common" },
      ],
      airLife: [{ marker: "bird", label: { ru: "современные птицы", en: "modern birds" }, status: "common" }],
      colors: ["#c6d7dd", "#7b8966", "#53879a"],
    },
    {
      fromMa: 0.3,
      toMa: 0.01,
      title: { ru: "Homo sapiens и поздний ледниковый мир", en: "Homo sapiens and the late ice-age world" },
      period: { ru: "поздний четвертичный период", en: "Late Quaternary" },
      headline: { ru: "Наш вид расселяется по планете, создает сложную культуру и приходит к земледелию", en: "Our species spreads worldwide, builds complex culture, and reaches agriculture" },
      atmosphere: { ru: "Последнее оледенение сменяется современным теплым межледниковьем.", en: "The last glaciation gives way to the present warm interglacial." },
      land: { ru: "Люди заселяют материки; многие крупные животные исчезают; в конце интервала начинается земледелие.", en: "Humans settle the continents; many large animals disappear; agriculture begins near the interval's end." },
      sea: { ru: "После таяния ледников море затапливает шельфы и принимает современные очертания.", en: "Melting ice floods continental shelves and gives seas their modern outlines." },
      landLife: [
        { marker: "human", label: { ru: "Homo sapiens", en: "Homo sapiens" }, status: "common" },
        { marker: "paint", label: { ru: "символическая культура", en: "symbolic culture" }, status: "new" },
        { marker: "grain", label: { ru: "земледелие", en: "agriculture" }, status: "new" },
      ],
      seaLife: [
        { marker: "fin", label: { ru: "современные рыбы", en: "modern fish" }, status: "common" },
        { marker: "mammal", label: { ru: "морские млекопитающие", en: "marine mammals" }, status: "common" },
      ],
      airLife: [
        { marker: "bird", label: { ru: "птицы", en: "birds" }, status: "common" },
        { marker: "animal", label: { ru: "насекомые", en: "insects" }, status: "common" },
      ],
      colors: ["#ccdce1", "#78875f", "#528799"],
    },
  ],
};
