window.EVOL_MODEL = {
  cardFlags: {
    bacteria: { local: true },
    amoeba: { local: true },
    mushroom: { local: true },
    oak: { local: true },
    moss: { local: true },
    pine: { local: true },
    fern: { local: true },
    horsetail: { local: true },
    grass: { local: true },
    earthworm: { local: true },
    slug: { local: true },
    bee: { local: true },
    ant: { local: true },
    butterfly: { local: true },
    mosquito: { local: true },
    dragonfly: { local: true },
    grasshopper: { local: true },
    ladybird: { local: true },
    wasp: { local: true },
    fly: { local: true },
    springtail: { local: true },
    silverfish: { local: true },
    spider: { local: true },
    crayfish: { local: true },
    lamprey: { local: true },
    perch: { local: true },
    frog: { local: true },
    lizard: { local: true },
    snake: { local: true },
    sparrow: { local: true },
    raven: { local: true },
    mouse: { local: true },
    rabbit: { local: true },
    squirrel: { local: true },
    bat: { local: true },
    human: { local: true },
  },

  localFocus: {
    id: "local",
    title: "Рядом",
    description: "узлы родства существ, которых легче встретить рядом",
    kind: "local",
    filterOrder: 90,
    nodeIds: [
      "life",
      "eukaryotes",
      "green-plants",
      "land-plants",
      "vascular-plants",
      "seed-plants",
      "flowering-plants",
      "grasses",
      "fungi",
      "animals",
      "bilateria",
      "annelids",
      "mollusks",
      "arthropods",
      "terrestrial-arthropods",
      "chelicerates",
      "crustaceans",
      "hexapods",
      "insects",
      "winged-insects",
      "complete-metamorphosis",
      "hymenoptera",
      "social-insects",
      "diptera",
      "lepidoptera",
      "chordates",
      "craniates",
      "jawed-vertebrates",
      "bony-vertebrates",
      "ray-finned-fishes",
      "tetrapods",
      "amphibians",
      "amniotes",
      "lepidosaurs",
      "squamates",
      "birds",
      "modern-birds",
      "mammals",
      "placentals",
      "rodents",
      "bats",
    ],
  },

  nodeDetails: [
    {
      id: "life",
      node: "жизнь",
      title: "Живая клетка",
      appearedMa: 3800,
      level: "easy",
      novelty: "клетка с оболочкой, обменом веществ и копированием себя",
      effect: "появилась система, которая берет энергию, строит себя и оставляет потомков",
      mainExamples: ["bacteria"],
      sideLabel: "неживая Земля: камни, вода, минералы",
      marker: "microbe",
      filterTitle: "Все",
      filterOrder: 10,
      flags: { filter: true },
    },
    {
      id: "eukaryotes",
      node: "эукариоты",
      title: "Клетка с ядром",
      appearedMa: 2000,
      level: "easy",
      novelty: "ядро, органеллы и более крупная сложная клетка",
      effect: "внутри клетки появились рабочие отделы; это открыло путь растениям, грибам и животным",
      mainExamples: ["amoeba"],
      marker: "nucleus",
    },
    {
      id: "mitochondria",
      node: "эукариоты",
      title: "Митохондрии",
      appearedMa: 1900,
      level: "medium",
      novelty: "внутри клетки поселяются энергетические бактерии",
      effect: "клетка получает больше энергии для крупного тела, движения и сложной внутренней работы",
      mainExamples: ["amoeba"],
      marker: "microbe",
    },
    {
      id: "sexual-reproduction",
      node: "эукариоты",
      title: "Половое размножение",
      appearedMa: 1200,
      level: "hard",
      novelty: "потомок собирает наследственность от двух клеток",
      effect: "линии быстрее перебирают варианты и лучше отвечают на изменения среды",
      mainExamples: ["amoeba", "greenAlgae"],
      marker: "split",
    },
    {
      id: "photosynthesis",
      node: "прокариоты",
      title: "Фотосинтез",
      appearedMa: 3400,
      level: "medium",
      novelty: "клетки начинают брать энергию света",
      effect: "жизнь получает мощный источник энергии, а позже атмосфера меняется из-за кислорода",
      mainExamples: ["bacteria"],
      marker: "leaf",
    },
    {
      id: "oxygen-revolution",
      node: "прокариоты",
      title: "Кислородная революция",
      appearedMa: 2400,
      level: "hard",
      novelty: "кислород накапливается в океане и воздухе",
      effect: "для многих древних микробов это яд, но будущая сложная жизнь получает путь к мощному дыханию",
      mainExamples: ["bacteria"],
      marker: "oxygen",
    },
    {
      id: "archaeplastids",
      node: "архепластиды",
      title: "Фотосинтетическая эукариотическая ветка",
      appearedMa: 1600,
      level: "easy",
      novelty: "хлоропласты становятся постоянной частью клетки",
      effect: "будущие растения получают способ строить пищу из света",
      mainExamples: ["greenAlgae", "oak"],
      marker: "chloroplast",
    },
    {
      id: "green-plants",
      node: "зеленые растения",
      title: "Зеленые растения",
      appearedMa: 1000,
      level: "easy",
      novelty: "зеленые пигменты, запас крахмала и водорослевое многоклеточное тело",
      effect: "растительная линия становится заметной основой будущих водных и наземных экосистем",
      mainExamples: ["greenAlgae", "moss", "oak"],
      marker: "leaf",
      filterTitle: "Растения",
      filterOrder: 20,
      flags: { filter: true },
    },
    {
      id: "land-plants",
      node: "наземные растения",
      title: "Растения выходят на сушу",
      appearedMa: 470,
      level: "medium",
      novelty: "защита от высыхания, прочные споры и зародыш на материнском растении",
      effect: "суша начинает покрываться зелеными телами, будущей почвой и пищей для животных",
      mainExamples: ["moss", "fern", "pine"],
      marker: "spore",
    },
    {
      id: "vascular-plants",
      node: "сосудистые растения",
      title: "Сосуды растений",
      appearedMa: 420,
      level: "medium",
      novelty: "трубки для воды, сахаров и минеральных веществ",
      effect: "растения могут расти выше и жить дальше от воды",
      mainExamples: ["fern", "horsetail", "oak"],
      marker: "vascular",
    },
    {
      id: "seed-plants",
      node: "семенные растения",
      title: "Семена",
      appearedMa: 355,
      level: "medium",
      novelty: "зародыш с запасом пищи и защитной оболочкой",
      effect: "размножение растений меньше зависит от открытой воды",
      mainExamples: ["pine", "oak"],
      marker: "seed",
    },
    {
      id: "flowering-plants",
      node: "цветковые",
      title: "Цветок и плод",
      appearedMa: 140,
      level: "hard",
      novelty: "цветок привлекает помощников, плод помогает распространять семена",
      effect: "цветковые быстро занимают множество наземных ниш",
      mainExamples: ["oak", "grass", "magnolia"],
      marker: "fruit",
    },
    {
      id: "grasses",
      node: "злаки",
      title: "Злаки",
      appearedMa: 70,
      level: "medium",
      novelty: "травянистый рост, узкие листья и питательные зерна",
      effect: "злаки создают луга и степи, кормят множество животных и позже становятся основой земледелия",
      mainExamples: ["grass"],
      marker: "grass",
    },
    {
      id: "opisthokonts",
      node: "опистоконты",
      title: "Общая ветка грибов и животных",
      appearedMa: 900,
      level: "medium",
      novelty: "питание готовой органикой и древняя связь грибов с животными",
      effect: "дальше одна сторона даст грибы, другая - активных животных",
      mainExamples: ["mushroom", "choanoflagellate", "sponge"],
      marker: "fork",
    },
    {
      id: "fungi",
      node: "грибы",
      title: "Грибы",
      appearedMa: 760,
      level: "easy",
      novelty: "грибница, наружное переваривание и всасывание готовой пищи",
      effect: "грибы становятся главными разлагателями и партнерами растений",
      mainExamples: ["mushroom"],
      marker: "fungus",
      filterTitle: "Грибы",
    },
    {
      id: "animals",
      node: "животные",
      title: "Многоклеточные животные",
      appearedMa: 650,
      level: "easy",
      novelty: "много клеток работают как одно тело",
      effect: "становятся возможны ткани, органы, движение и поведение",
      mainExamples: ["sponge", "jellyfish", "earthworm"],
      marker: "algae",
      filterTitle: "Животные",
      filterOrder: 30,
      flags: { filter: true },
    },
    {
      id: "nervous-system",
      node: "животные",
      title: "Нервная система",
      appearedMa: 580,
      level: "medium",
      novelty: "клетки начинают быстро передавать сигналы по телу",
      effect: "животные быстрее чувствуют мир, двигаются и связывают части тела в одно поведение",
      mainExamples: ["jellyfish", "earthworm"],
      marker: "animal",
    },
    {
      id: "bilateria",
      node: "билатерии",
      title: "Двустороннее тело",
      appearedMa: 560,
      level: "easy",
      novelty: "перед, зад, левая и правая сторона",
      effect: "животному удобнее двигаться вперед, искать еду и собирать органы чувств спереди",
      mainExamples: ["planarian", "earthworm", "lancelet"],
      marker: "bilateral",
    },
    {
      id: "hard-skeletons",
      node: "билатерии",
      title: "Панцири и скелеты",
      appearedMa: 540,
      level: "medium",
      novelty: "твердые защитные и опорные части тела",
      effect: "начинается гонка защиты, нападения и более сильного движения",
      mainExamples: ["nautilus", "slug", "horseshoeCrab"],
      marker: "exoskeleton",
    },
    {
      id: "protostomes",
      node: "первичноротые",
      title: "Первичноротые",
      appearedMa: 540,
      level: "medium",
      novelty: "один из двух больших планов развития билатерий",
      effect: "эта ветка даст моллюсков, червей, членистоногих и большую часть животных видов",
      mainExamples: ["slug", "earthworm", "horseshoeCrab"],
      marker: "fork",
      filterTitle: "Первичноротые",
      filterOrder: 40,
      flags: { filter: true },
    },
    {
      id: "mollusks",
      node: "моллюски",
      title: "Моллюски",
      appearedMa: 530,
      level: "easy",
      novelty: "мягкое тело, мускулистая нога и часто раковина",
      effect: "эта ветка дает улиток, слизней, двустворок, осьминогов и наутилусов",
      mainExamples: ["slug", "octopus", "nautilus"],
      marker: "fork",
      filterTitle: "Моллюски",
    },
    {
      id: "annelids",
      node: "кольчатые черви",
      title: "Кольчатые черви",
      appearedMa: 520,
      level: "medium",
      novelty: "тело из повторяющихся сегментов",
      effect: "сегменты помогают ползать, рыть и строить длинное гибкое тело",
      mainExamples: ["earthworm"],
      marker: "worm",
    },
    {
      id: "arthropods",
      node: "членистоногие",
      title: "Членистоногие",
      appearedMa: 520,
      level: "easy",
      novelty: "наружный скелет и суставчатые ноги",
      effect: "тело хорошо защищено и удобно для ходьбы, плавания, хватания и полета",
      mainExamples: ["horseshoeCrab", "spider", "crayfish"],
      marker: "beetle",
      filterTitle: "Артроподы",
    },
    {
      id: "chelicerates",
      node: "хелицеровые",
      title: "Хелицеровые",
      appearedMa: 500,
      level: "medium",
      novelty: "нет усиков, первая пара придатков работает как хелицеры",
      effect: "эта ветка дает пауков, скорпионов, клещей и мечехвостов",
      mainExamples: ["spider", "horseshoeCrab"],
      marker: "fork",
    },
    {
      id: "crustaceans",
      node: "ракообразные",
      title: "Ракообразные",
      appearedMa: 510,
      level: "medium",
      novelty: "водная членистоногая ветка с двумя парами усиков",
      effect: "ракообразные занимают множество морских и пресноводных ролей",
      mainExamples: ["crayfish"],
      marker: "fork",
    },
    {
      id: "hexapods",
      node: "шестиногие",
      title: "Шестиногие",
      appearedMa: 420,
      level: "medium",
      novelty: "тело с шестью ногами и жизнью среди почвы, растений и воздуха",
      effect: "эта ветка ведет к насекомым и их близким родственникам",
      mainExamples: ["springtail", "silverfish", "dragonfly"],
      marker: "sixlegs",
    },
    {
      id: "insects",
      node: "насекомые",
      title: "Насекомые",
      appearedMa: 410,
      level: "easy",
      novelty: "шесть ног, усики и компактное сухопутное тело",
      effect: "насекомые становятся одной из самых заметных и богатых видами веток суши",
      mainExamples: ["silverfish", "dragonfly", "grasshopper"],
      marker: "insect",
    },
    {
      id: "terrestrial-arthropods",
      node: "членистоногие",
      title: "Членистоногие на суше",
      appearedMa: 430,
      level: "medium",
      novelty: "панцирь удерживает воду, а ноги несут тело по суше",
      effect: "суша получает первых заметных ползающих животных задолго до крупных позвоночных",
      mainExamples: ["spider", "horseshoeCrab", "silverfish"],
      marker: "footprint",
    },
    {
      id: "winged-insects",
      node: "крылатые насекомые",
      title: "Крылатые насекомые",
      appearedMa: 400,
      level: "hard",
      novelty: "полет на крыльях",
      effect: "насекомые быстрее находят пищу, пары и новые места",
      mainExamples: ["dragonfly", "butterfly", "fly"],
      marker: "wing",
    },
    {
      id: "complete-metamorphosis",
      node: "насекомые",
      title: "Полное превращение",
      appearedMa: 350,
      level: "hard",
      novelty: "личинка и взрослое насекомое живут по-разному",
      effect: "дети и взрослые меньше конкурируют и могут использовать разные источники пищи",
      mainExamples: ["butterfly", "fly", "bee"],
      marker: "metamorphosis",
    },
    {
      id: "beetles",
      node: "жуки",
      title: "Жуки",
      appearedMa: 300,
      level: "hard",
      novelty: "передние крылья превращаются в твердые надкрылья",
      effect: "жуки получают защиту для тела и задних летательных крыльев",
      mainExamples: ["ladybird"],
      marker: "beetle",
    },
    {
      id: "hymenoptera",
      node: "перепончатокрылые",
      title: "Перепончатокрылые",
      appearedMa: 250,
      level: "hard",
      novelty: "тонкие перепончатые крылья и сложное поведение",
      effect: "эта ветка дает пчел, ос, муравьев и множество общественных форм",
      mainExamples: ["bee", "ant", "wasp"],
      marker: "ant",
    },
    {
      id: "social-insects",
      node: "перепончатокрылые",
      title: "Общественные насекомые",
      appearedMa: 100,
      level: "hard",
      novelty: "колония с разделением работы",
      effect: "семья работает как большой организм: строит, ищет пищу и защищается вместе",
      mainExamples: ["ant", "bee", "wasp"],
      marker: "ant",
    },
    {
      id: "diptera",
      node: "двукрылые",
      title: "Двукрылые",
      appearedMa: 245,
      level: "hard",
      novelty: "одна пара крыльев и балансиры вместо второй пары",
      effect: "мухи и комары становятся быстрыми и маневренными летунами",
      mainExamples: ["fly", "mosquito"],
      marker: "mosquito",
    },
    {
      id: "lepidoptera",
      node: "чешуекрылые",
      title: "Чешуекрылые",
      appearedMa: 200,
      level: "hard",
      novelty: "крылья с чешуйками и личинка-гусеница",
      effect: "взрослые и личинки могут жить на разных ресурсах",
      mainExamples: ["butterfly"],
      marker: "butterfly",
    },
    {
      id: "deuterostomes",
      node: "вторичноротые",
      title: "Вторичноротые",
      appearedMa: 540,
      level: "medium",
      novelty: "другой план раннего развития зародыша",
      effect: "в этой ветке появляются иглокожие, хордовые и позвоночные",
      mainExamples: ["starfish", "lancelet"],
      marker: "star",
      filterTitle: "Вторичноротые",
      filterOrder: 50,
      flags: { filter: true },
    },
    {
      id: "chordates",
      node: "хордовые",
      title: "Хорда",
      appearedMa: 530,
      level: "easy",
      novelty: "внутренняя упругая ось вдоль тела",
      effect: "по этой оси легче строить плавание, движение и будущий позвоночник",
      mainExamples: ["lancelet", "lamprey", "perch"],
      marker: "chord",
      filterTitle: "Хордовые",
    },
    {
      id: "craniates",
      node: "черепные",
      title: "Череп",
      appearedMa: 520,
      level: "medium",
      novelty: "передний конец тела получает защиту для мозга и органов чувств",
      effect: "голова становится важным центром управления",
      mainExamples: ["lamprey", "perch"],
      marker: "skull",
    },
    {
      id: "jawed-vertebrates",
      node: "челюстноротые",
      title: "Челюсти",
      appearedMa: 430,
      level: "medium",
      novelty: "рот становится хватательным и кусательным",
      effect: "можно удерживать добычу и активнее питаться",
      mainExamples: ["dunkleosteus", "perch", "shark"],
      marker: "jaw",
    },
    {
      id: "bony-vertebrates",
      node: "костные позвоночные",
      title: "Костная линия",
      appearedMa: 425,
      level: "easy",
      novelty: "внутри тела становится много прочной кости",
      effect: "позвоночные получают прочную опору; отсюда пойдут большинство рыб и наземные животные",
      mainExamples: ["perch", "coelacanth", "frog"],
      marker: "bone",
    },
    {
      id: "ray-finned-fishes",
      node: "лучеперые",
      title: "Лучеперые рыбы",
      appearedMa: 420,
      level: "medium",
      novelty: "плавники держатся на тонких лучах",
      effect: "эта ветка становится самой богатой видами рыбной линией современных водоемов",
      mainExamples: ["perch"],
      marker: "fin",
    },
    {
      id: "lobe-fins",
      node: "лопастеперые",
      title: "Лопастные плавники",
      appearedMa: 400,
      level: "hard",
      novelty: "плавники с внутренними костями",
      effect: "эта конструкция станет основой для конечностей",
      mainExamples: ["coelacanth", "lungfish", "tiktaalik"],
      marker: "fin",
    },
    {
      id: "tetrapods",
      node: "четвероногие",
      title: "Конечности",
      appearedMa: 375,
      level: "easy",
      novelty: "четыре опорные конечности вместо одних плавников",
      effect: "позвоночные получают путь к мелководью и суше",
      mainExamples: ["tiktaalik", "frog", "lizard"],
      marker: "limb",
    },
    {
      id: "amphibians",
      node: "амфибии",
      title: "Амфибии",
      appearedMa: 370,
      level: "medium",
      novelty: "четвероногая жизнь, сильно связанная с водой и влажной кожей",
      effect: "амфибии занимают границу воды и суши",
      mainExamples: ["frog", "axolotl"],
      marker: "limb",
    },
    {
      id: "amniotes",
      node: "амниоты",
      title: "Амниотическое яйцо",
      appearedMa: 320,
      level: "easy",
      novelty: "зародыш развивается в защитных оболочках",
      effect: "размножение меньше зависит от воды",
      mainExamples: ["lizard", "sparrow", "mouse"],
      marker: "egg",
    },
    {
      id: "synapsids",
      node: "синапсиды",
      title: "Синапсидный череп",
      appearedMa: 315,
      level: "easy",
      novelty: "одно височное окно за глазом",
      effect: "челюстные мышцы получают новые места крепления; эта ветка ведет к млекопитающим",
      mainExamples: ["dimetrodon", "mouse", "human"],
      marker: "split",
      filterTitle: "Синапсиды",
      filterOrder: 70,
      flags: { filter: true },
    },
    {
      id: "sauropsids",
      node: "завропсиды",
      title: "Завропсидная сторона амниот",
      appearedMa: 315,
      level: "easy",
      novelty: "другая большая амниотическая дорога",
      effect: "эта сторона даст ящериц, змей, крокодилов, динозавров и птиц",
      mainExamples: ["lizard", "crocodile", "sparrow"],
      marker: "split",
      filterTitle: "Диапсиды",
      filterOrder: 60,
      flags: { filter: true },
    },
    {
      id: "diapsid-skull",
      node: "завропсиды",
      title: "Диапсидные окна",
      appearedMa: 295,
      level: "medium",
      novelty: "два височных окна за глазом",
      effect: "череп становится легче, а челюстные мышцы получают удобные места крепления",
      mainExamples: ["lizard", "crocodile", "sparrow"],
      marker: "skull",
    },
    {
      id: "mammals",
      node: "млекопитающие",
      title: "Млекопитающие",
      appearedMa: 220,
      level: "easy",
      novelty: "шерсть, молоко и более теплое тело",
      effect: "детенышей проще кормить и защищать, а маленькое ночное тело получает преимущество",
      mainExamples: ["morganucodon", "mouse", "bat"],
      marker: "mammal",
    },
    {
      id: "monotremes",
      node: "однопроходные",
      title: "Однопроходные",
      appearedMa: 170,
      level: "medium",
      novelty: "млекопитающие, которые сохраняют яйцекладку",
      effect: "утконос и ехидна показывают древнюю сторону разнообразия млекопитающих",
      mainExamples: ["platypus", "echidna"],
      marker: "egg",
    },
    {
      id: "therians",
      node: "звери",
      title: "Звери",
      appearedMa: 170,
      level: "medium",
      novelty: "детеныш развивается в теле матери",
      effect: "эта ветка дает сумчатых и плацентарных",
      mainExamples: ["kangaroo", "mouse", "human"],
      marker: "mammal",
    },
    {
      id: "marsupials",
      node: "сумчатые",
      title: "Сумчатые",
      appearedMa: 125,
      level: "medium",
      novelty: "детеныш рождается очень рано и доразвивается у матери",
      effect: "сумчатые занимают множество ролей, особенно в Австралии и Америке",
      mainExamples: ["kangaroo", "koala"],
      marker: "mammal",
    },
    {
      id: "placentals",
      node: "плацентарные",
      title: "Плацентарные",
      appearedMa: 160,
      level: "easy",
      novelty: "долгое питание детеныша через плаценту",
      effect: "детеныш может дольше развиваться внутри тела и рождаться более подготовленным",
      mainExamples: ["mouse", "rabbit", "human"],
      marker: "mammal",
    },
    {
      id: "archosaurs",
      node: "архозавры",
      title: "Архозавры",
      appearedMa: 250,
      level: "medium",
      novelty: "более активная стойка и шаг",
      effect: "эта линия даст крокодилов, птерозавров, динозавров и птиц",
      mainExamples: ["crocodile", "pteranodon", "sparrow"],
      marker: "dino",
    },
    {
      id: "lepidosaurs",
      node: "лепидозавры",
      title: "Лепидозавры",
      appearedMa: 240,
      level: "medium",
      novelty: "завропсидная ветка ящериц, змей и гаттерии",
      effect: "эта линия становится очень заметной среди современных рептилий",
      mainExamples: ["tuatara", "lizard", "snake"],
      marker: "fork",
    },
    {
      id: "squamates",
      node: "чешуйчатые",
      title: "Чешуйчатые",
      appearedMa: 190,
      level: "hard",
      novelty: "подвижный череп и чешуйчатое тело у ящериц и змей",
      effect: "ящерицы и змеи занимают множество наземных, древесных и водных ниш",
      mainExamples: ["lizard", "snake"],
      marker: "fork",
    },
    {
      id: "pseudosuchians",
      node: "псевдозухии",
      title: "Крокодилья сторона архозавров",
      appearedMa: 250,
      level: "medium",
      novelty: "архозавровая ветка к крокодилам и их древним родственникам",
      effect: "полуводные хищники переживают кризисы и остаются рядом с птицами как родственники",
      mainExamples: ["prestosuchus", "crocodile", "alligator"],
      marker: "fork",
    },
    {
      id: "pterosaurs",
      node: "птерозавры",
      title: "Птерозавры",
      appearedMa: 228,
      level: "medium",
      novelty: "крыло из кожи на удлиненном пальце",
      effect: "позвоночные впервые становятся активными летунами",
      mainExamples: ["pteranodon"],
      marker: "bird",
    },
    {
      id: "dinosaurs",
      node: "динозавры",
      title: "Динозавры",
      appearedMa: 235,
      level: "easy",
      novelty: "ноги стоят под телом",
      effect: "ходьба становится мощной и экономной; динозавры занимают множество наземных ролей",
      mainExamples: ["herrerasaurus", "triceratops", "sparrow"],
      marker: "dino",
      filterTitle: "Динозавры",
    },
    {
      id: "theropods",
      node: "тероподы",
      title: "Тероподы",
      appearedMa: 230,
      level: "medium",
      novelty: "двуногие хищные динозавры с активным движением",
      effect: "одна тероподовая линия постепенно идет к птицам",
      mainExamples: ["allosaurus", "velociraptor", "sparrow"],
      marker: "dino",
    },
    {
      id: "theropod-feathers",
      node: "тероподы",
      title: "Перья у теропод",
      appearedMa: 170,
      level: "hard",
      novelty: "перья сначала работают как покров, сигнал и теплоизоляция",
      effect: "готовая перьевая конструкция позже становится частью птичьего крыла",
      mainExamples: ["velociraptor", "archaeopteryx", "sparrow"],
      marker: "bird",
    },
    {
      id: "birds",
      node: "птицы",
      title: "Птицы",
      appearedMa: 150,
      level: "easy",
      novelty: "перья и крылья в птичьей линии динозавров",
      effect: "полет и теплоизоляция открывают новую жизнь в воздухе",
      mainExamples: ["archaeopteryx", "sparrow", "raven"],
      marker: "bird",
    },
    {
      id: "modern-birds",
      node: "птицы",
      title: "Современные птицы",
      appearedMa: 100,
      level: "medium",
      novelty: "клюв, короткий хвост и легкое тело",
      effect: "птицы становятся разнообразными летающими, плавающими и бегающими динозаврами",
      mainExamples: ["sparrow", "raven"],
      marker: "bird",
    },
    {
      id: "primates",
      node: "приматы",
      title: "Приматы",
      appearedMa: 55,
      level: "easy",
      novelty: "цепкие руки, глаза вперед и обучение",
      effect: "жизнь на ветках становится удобнее, а поведение сложнее",
      mainExamples: ["lemur", "macaque", "human"],
      marker: "ape",
      filterTitle: "Приматы",
    },
    {
      id: "rodents",
      node: "грызуны",
      title: "Грызуны",
      appearedMa: 60,
      level: "medium",
      novelty: "постоянно растущие резцы для грызения",
      effect: "грызуны становятся одной из самых успешных веток плацентарных",
      mainExamples: ["mouse", "squirrel", "nakedMoleRat"],
      marker: "mammal",
    },
    {
      id: "bats",
      node: "рукокрылые",
      title: "Летучие мыши",
      appearedMa: 55,
      level: "hard",
      novelty: "крыло из кожи между пальцами",
      effect: "млекопитающие занимают ночной воздух и охоту в полете",
      mainExamples: ["bat"],
      marker: "bird",
    },
    {
      id: "whales",
      node: "китообразные",
      title: "Киты уходят в море",
      appearedMa: 50,
      level: "hard",
      novelty: "млекопитающее тело снова становится водным",
      effect: "теплокровность, дыхание воздухом и живорождение начинают работать в океане",
      mainExamples: ["whale"],
      marker: "ocean",
    },
    {
      id: "monkeys",
      node: "обезьяны",
      title: "Обезьяны",
      appearedMa: 40,
      level: "medium",
      novelty: "дневное зрение, хватание и сложная социальная жизнь",
      effect: "приматы становятся активными древесными и наземными животными",
      mainExamples: ["macaque", "baboon", "human"],
      marker: "monkey",
    },
    {
      id: "apes",
      node: "человекообразные",
      title: "Человекообразные",
      appearedMa: 20,
      level: "medium",
      novelty: "нет хвоста, гибкие плечи и крупный мозг",
      effect: "руки становятся особенно важны для лазания, хватания и обучения",
      mainExamples: ["orangutan", "chimpanzee", "human"],
      marker: "ape",
    },
    {
      id: "hominins",
      node: "люди",
      title: "Прямохождение",
      appearedMa: 6,
      level: "easy",
      novelty: "наша линия все чаще ходит на двух ногах",
      effect: "руки освобождаются, обзор над травой становится лучше, переносить еду и детенышей удобнее",
      mainExamples: ["human"],
      image: "assets/photos/homo-erectus.jpg",
      imageLabel: "пример: прямоходящая человеческая линия",
      marker: "footprint",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "stone-tools",
      node: "люди",
      title: "Каменные орудия",
      appearedMa: 3.3,
      level: "medium",
      novelty: "предмет специально меняют под задачу",
      effect: "руки, мозг и обучение начинают сильнее менять поведение нашей линии",
      mainExamples: ["human"],
      image: "assets/photos/log-stone-tool.jpg",
      imageLabel: "пример: древнее каменное орудие",
      marker: "handaxe",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "controlled-fire",
      node: "люди",
      title: "Управление огнем",
      appearedMa: 1,
      level: "medium",
      novelty: "огонь становится частью жизни людей",
      effect: "тепло, свет, защита и приготовление пищи меняют стоянки и общение",
      mainExamples: ["human"],
      image: "assets/photos/log-lascaux.jpg",
      imageLabel: "пример: стоянка, свет и огонь",
      marker: "torch",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "humans",
      node: "люди",
      title: "Homo sapiens",
      appearedMa: 0.3,
      level: "easy",
      novelty: "наш вид и очень сильная культурная передача",
      effect: "обучение и речь меняют жизнь быстрее, чем большинство биологических процессов",
      mainExamples: ["human"],
      marker: "child",
      filterTitle: "Человек",
      filterOrder: 80,
      flags: { filter: true, focusOnly: ["humans"] },
    },
    {
      id: "symbolic-art",
      node: "люди",
      title: "Символы и искусство",
      appearedMa: 0.04,
      level: "hard",
      novelty: "рисунки, украшения и знаки",
      effect: "память группы становится видимой и может передаваться через предметы и изображения",
      mainExamples: ["human"],
      image: "assets/photos/log-lascaux.jpg",
      imageLabel: "пример: пещерное искусство",
      marker: "paint",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "agriculture",
      node: "люди",
      title: "Земледелие",
      appearedMa: 0.012,
      level: "easy",
      novelty: "люди выращивают растения и меняют ландшафт",
      effect: "пища планируется заранее; появляются поселения, запасы и новые общества",
      mainExamples: ["human", "grass"],
      image: "assets/photos/log-wheat.jpg",
      imageLabel: "пример: зерно и выращивание растений",
      marker: "grain",
      flags: { focusOnly: ["humans"] },
    },
  ],
};
