window.EVOL_MODEL = {
  cardFlags: {
    bacteria: { local: true },
    amoeba: { local: true },
    mushroom: { local: true },
    oak: { local: true },
    moss: { local: true },
    pine: { local: true },
    fern: { local: true },
    horsetail: { local: true },
    grass: { local: true },
    earthworm: { local: true },
    slug: { local: true },
    bee: { local: true },
    ant: { local: true },
    butterfly: { local: true },
    mosquito: { local: true },
    dragonfly: { local: true },
    grasshopper: { local: true },
    ladybird: { local: true },
    wasp: { local: true },
    fly: { local: true },
    springtail: { local: true },
    silverfish: { local: true },
    spider: { local: true },
    crayfish: { local: true },
    lamprey: { local: true },
    perch: { local: true },
    frog: { local: true },
    lizard: { local: true },
    snake: { local: true },
    sparrow: { local: true },
    raven: { local: true },
    mouse: { local: true },
    rabbit: { local: true },
    squirrel: { local: true },
    bat: { local: true },
    human: { local: true },
  },

  localFocus: {
    id: "local",
    title: "Рядом",
    description: "узлы родства существ, которых легче встретить рядом",
    kind: "local",
    defaultScope: "all",
    filterOrder: 90,
    nodeIds: [
      "life",
      "eukaryotes",
      "green-plants",
      "land-plants",
      "vascular-plants",
      "seed-plants",
      "gymnosperms",
      "flowering-plants",
      "grasses",
      "fungi",
      "animals",
      "bilateria",
      "annelids",
      "mollusks",
      "arthropods",
      "terrestrial-arthropods",
      "chelicerates",
      "crustaceans",
      "hexapods",
      "insects",
      "winged-insects",
      "complete-metamorphosis",
      "hymenoptera",
      "social-insects",
      "diptera",
      "lepidoptera",
      "chordates",
      "craniates",
      "jawless-vertebrates",
      "jawed-vertebrates",
      "bony-vertebrates",
      "ray-finned-fishes",
      "tetrapods",
      "amphibians",
      "amniotes",
      "lepidosaurs",
      "squamates",
      "birds",
      "modern-birds",
      "mammals",
      "placentals",
      "rodents",
      "bats",
    ],
  },

  scopeOptions: [
    { id: "main", title: "Главное", description: "только самые крупные вехи" },
    { id: "detail", title: "Подробнее", description: "крупные и важные ветвевые события" },
    { id: "all", title: "Все", description: "все события выбранной ветки" },
  ],

  importanceById: {
    life: "global",
    photosynthesis: "global",
    "oxygen-revolution": "global",
    eukaryotes: "global",
    mitochondria: "major",
    "sexual-reproduction": "major",
    archaeplastids: "global",
    "green-plants": "global",
    streptophytes: "branch",
    "land-plants": "major",
    "vascular-plants": "major",
    megaphylls: "fine",
    "seed-plants": "major",
    gymnosperms: "branch",
    "flowering-plants": "major",
    "modern-flowering-plants": "fine",
    grasses: "branch",
    opisthokonts: "global",
    fungi: "major",
    animals: "global",
    "nervous-system": "major",
    bilateria: "global",
    "hard-skeletons": "major",
    protostomes: "global",
    mollusks: "major",
    cephalopods: "branch",
    annelids: "branch",
    ecdysozoans: "major",
    panarthropods: "branch",
    arthropods: "major",
    chelicerates: "branch",
    crustaceans: "branch",
    hexapods: "branch",
    insects: "major",
    "terrestrial-arthropods": "branch",
    "winged-insects": "branch",
    "complete-metamorphosis": "fine",
    beetles: "fine",
    hymenoptera: "fine",
    "social-insects": "fine",
    diptera: "fine",
    lepidoptera: "fine",
    deuterostomes: "global",
    echinoderms: "branch",
    chordates: "global",
    craniates: "major",
    "jawless-vertebrates": "branch",
    "jawed-vertebrates": "major",
    "cartilaginous-fishes": "branch",
    "bony-vertebrates": "major",
    "ray-finned-fishes": "branch",
    "lobe-fins": "major",
    tetrapods: "global",
    amphibians: "branch",
    amniotes: "global",
    synapsids: "global",
    therapsids: "branch",
    cynodonts: "branch",
    mammaliaforms: "branch",
    sauropsids: "global",
    "diapsid-skull": "major",
    mammals: "major",
    monotremes: "branch",
    therians: "branch",
    marsupials: "branch",
    placentals: "major",
    laurasiatherians: "fine",
    archosaurs: "major",
    lepidosaurs: "branch",
    squamates: "fine",
    pseudosuchians: "branch",
    crocodilians: "fine",
    avemetatarsalians: "branch",
    pterosaurs: "branch",
    dinosauromorphs: "fine",
    dinosaurs: "major",
    saurischians: "branch",
    theropods: "branch",
    coelurosaurs: "fine",
    "theropod-feathers": "fine",
    avialans: "fine",
    birds: "major",
    "modern-birds": "branch",
    primates: "major",
    rodents: "fine",
    bats: "fine",
    whales: "fine",
    monkeys: "branch",
    catarrhines: "fine",
    apes: "branch",
    "late-apes": "fine",
    hominins: "major",
    "early-homo": "fine",
    "homo-erectus": "fine",
    "stone-tools": "branch",
    "controlled-fire": "branch",
    humans: "major",
    "sapiens-expansion": "fine",
    migration: "fine",
    "symbolic-art": "fine",
    "late-ice-age": "fine",
    agriculture: "fine",
    "writing-cities": "fine",
    "ancient-states": "fine",
    "medieval-world": "fine",
    printing: "fine",
    "scientific-revolution": "fine",
    industrialization: "fine",
    "electric-world": "fine",
    computers: "fine",
    internet: "fine",
    smartphones: "fine",
    "cloud-culture": "fine",
    "generative-ai": "fine",
    "heavy-elements": "global",
    earth: "global",
  },

  nodeDetails: [
    {
      id: "heavy-elements",
      node: "космос",
      title: "Тяжелые элементы",
      appearedMa: 10000,
      level: "easy",
      novelty: "звезды создают тяжелые атомы для будущих планет",
      effect: "без углерода, кислорода, железа и других элементов не будет камней, воды и химии жизни",
      mainExamples: [],
      image: "assets/photos/log-milky-way.jpg",
      imageLabel: "космос до появления Земли",
      marker: "star",
    },
    {
      id: "earth",
      node: "Земля",
      title: "Земля",
      appearedMa: 4540,
      level: "easy",
      novelty: "формируется планета с каменной поверхностью, водой и химической сценой",
      effect: "появляется место, где позже смогут возникнуть устойчивые молекулы и клетки",
      mainExamples: [],
      image: "assets/photos/early-earth.svg",
      imageLabel: "молодая Земля с океанами и вулканами",
      marker: "earth",
    },
    {
      id: "life",
      node: "жизнь",
      title: "Живая клетка",
      appearedMa: 3800,
      level: "easy",
      novelty: "клетка с оболочкой, обменом веществ и копированием себя",
      effect: "появилась система, которая берет энергию, строит себя и оставляет потомков",
      mainExamples: ["bacteria"],
      sideLabel: "неживая Земля: камни, вода, минералы",
      marker: "microbe",
      filterTitle: "Все",
      filterOrder: 10,
      defaultScope: "main",
      flags: { filter: true },
    },
    {
      id: "eukaryotes",
      node: "эукариоты",
      title: "Клетка с ядром",
      appearedMa: 2000,
      level: "easy",
      novelty: "ядро, органеллы и более крупная сложная клетка",
      effect: "внутри клетки появились рабочие отделы; это открыло путь растениям, грибам и животным",
      mainExamples: ["amoeba"],
      marker: "nucleus",
    },
    {
      id: "mitochondria",
      node: "эукариоты",
      title: "Митохондрии",
      appearedMa: 1900,
      level: "medium",
      novelty: "внутри клетки поселяются энергетические бактерии",
      effect: "клетка получает больше энергии для крупного тела, движения и сложной внутренней работы",
      mainExamples: ["amoeba"],
      marker: "microbe",
    },
    {
      id: "sexual-reproduction",
      node: "эукариоты",
      title: "Мейоз и половое размножение",
      appearedMa: 1800,
      level: "hard",
      novelty: "мейоз перемешивает наследственность перед новым поколением",
      effect: "эукариоты быстрее перебирают варианты и лучше отвечают на изменения среды",
      mainExamples: ["amoeba", "greenAlgae"],
      marker: "split",
    },
    {
      id: "photosynthesis",
      node: "прокариоты",
      title: "Фотосинтез",
      appearedMa: 3400,
      level: "medium",
      novelty: "клетки начинают брать энергию света",
      effect: "жизнь получает мощный источник энергии, а позже атмосфера меняется из-за кислорода",
      mainExamples: ["bacteria"],
      marker: "leaf",
    },
    {
      id: "oxygen-revolution",
      node: "прокариоты",
      title: "Кислородная революция",
      appearedMa: 2400,
      level: "hard",
      novelty: "кислород накапливается в океане и воздухе",
      effect: "для многих древних микробов это яд, но будущая сложная жизнь получает путь к мощному дыханию",
      mainExamples: ["bacteria"],
      marker: "oxygen",
    },
    {
      id: "archaeplastids",
      node: "архепластиды",
      title: "Первичные хлоропласты",
      appearedMa: 1600,
      level: "easy",
      novelty: "эукариотическая клетка получает постоянного фотосинтезирующего симбионта",
      effect: "архепластиды получают хлоропласты; отсюда пойдут красные водоросли, зеленые водоросли и наземные растения",
      mainExamples: ["greenAlgae", "oak"],
      marker: "chloroplast",
    },
    {
      id: "green-plants",
      node: "зеленые растения",
      title: "Зеленые растения",
      appearedMa: 1000,
      level: "easy",
      novelty: "зеленые пигменты, запас крахмала и водорослевое многоклеточное тело",
      effect: "растительная линия становится заметной основой будущих водных и наземных экосистем",
      mainExamples: ["greenAlgae", "moss", "oak"],
      marker: "leaf",
      filterTitle: "Растения",
      filterOrder: 20,
      defaultScope: "detail",
      flags: { filter: true },
    },
    {
      id: "streptophytes",
      node: "стрептофиты",
      title: "Стрептофиты",
      appearedMa: 800,
      level: "hard",
      novelty: "клетки лучше сцепляются, а споры и оболочки помогают жить у берега",
      effect: "стрептофиты становятся мостом от водорослей к наземным растениям",
      mainExamples: ["moss", "fern", "oak"],
      marker: "chara",
    },
    {
      id: "land-plants",
      node: "наземные растения",
      title: "Растения выходят на сушу",
      appearedMa: 470,
      level: "medium",
      novelty: "защита от высыхания, прочные споры и зародыш на материнском растении",
      effect: "суша начинает покрываться зелеными телами, будущей почвой и пищей для животных",
      mainExamples: ["moss", "fern", "pine"],
      marker: "spore",
    },
    {
      id: "vascular-plants",
      node: "сосудистые растения",
      title: "Сосуды растений",
      appearedMa: 420,
      level: "medium",
      novelty: "трубки для воды, сахаров и минеральных веществ",
      effect: "растения могут расти выше и жить дальше от воды",
      mainExamples: ["fern", "horsetail", "oak"],
      marker: "vascular",
    },
    {
      id: "megaphylls",
      node: "сосудистые растения",
      title: "Крупные листья",
      appearedMa: 400,
      level: "hard",
      novelty: "лист становится большой пластиной с жилками",
      effect: "растение собирает больше света и строит крупное тело",
      mainExamples: ["fern", "horsetail", "oak"],
      marker: "fern",
    },
    {
      id: "seed-plants",
      node: "семенные растения",
      title: "Семена",
      appearedMa: 355,
      level: "medium",
      novelty: "зародыш с запасом пищи и защитной оболочкой",
      effect: "размножение растений меньше зависит от открытой воды",
      mainExamples: ["pine", "oak"],
      marker: "seed",
    },
    {
      id: "gymnosperms",
      node: "голосеменные",
      title: "Голосеменные",
      appearedMa: 320,
      level: "hard",
      novelty: "пыльца, семязачатки и семена без цветка и плода",
      effect: "голосеменные дают хвойные деревья и долго остаются важной лесной веткой",
      mainExamples: ["pine"],
      marker: "seed",
    },
    {
      id: "flowering-plants",
      node: "цветковые",
      title: "Цветок и плод",
      appearedMa: 140,
      level: "hard",
      novelty: "цветок привлекает помощников, плод помогает распространять семена",
      effect: "цветковые быстро занимают множество наземных ниш",
      mainExamples: ["oak", "grass", "magnolia"],
      marker: "fruit",
    },
    {
      id: "modern-flowering-plants",
      node: "цветковые",
      title: "Современные цветковые",
      appearedMa: 125,
      level: "hard",
      novelty: "быстро расходятся крупные линии цветковых растений",
      effect: "цветковые становятся главной основой многих современных наземных экосистем",
      mainExamples: ["magnolia", "oak", "grass"],
      marker: "flower",
    },
    {
      id: "grasses",
      node: "злаки",
      title: "Злаки",
      appearedMa: 70,
      level: "medium",
      novelty: "травянистый рост, узкие листья и питательные зерна",
      effect: "злаки создают луга и степи, кормят множество животных и позже становятся основой земледелия",
      mainExamples: ["grass"],
      marker: "grass",
    },
    {
      id: "opisthokonts",
      node: "опистоконты",
      title: "Общая ветка грибов и животных",
      appearedMa: 900,
      level: "medium",
      novelty: "питание готовой органикой и древняя связь грибов с животными",
      effect: "опистоконты расходятся на грибы и активных животных",
      mainExamples: ["mushroom", "choanoflagellate", "sponge"],
      marker: "fork",
    },
    {
      id: "fungi",
      node: "грибы",
      title: "Грибы",
      appearedMa: 760,
      level: "easy",
      novelty: "грибница, наружное переваривание и всасывание готовой пищи",
      effect: "грибы становятся главными разлагателями и партнерами растений",
      mainExamples: ["mushroom"],
      marker: "fungus",
      filterTitle: "Грибы",
    },
    {
      id: "animals",
      node: "животные",
      title: "Многоклеточные животные",
      appearedMa: 650,
      level: "easy",
      novelty: "много клеток работают как одно тело",
      effect: "становятся возможны ткани, органы, движение и поведение",
      mainExamples: ["sponge", "jellyfish", "earthworm"],
      marker: "algae",
      filterTitle: "Животные",
      filterOrder: 30,
      defaultScope: "detail",
      flags: { filter: true },
    },
    {
      id: "nervous-system",
      node: "животные",
      title: "Нервная система",
      appearedMa: 580,
      level: "medium",
      novelty: "клетки начинают быстро передавать сигналы по телу",
      effect: "животные быстрее чувствуют мир, двигаются и связывают части тела в одно поведение",
      mainExamples: ["jellyfish", "earthworm"],
      marker: "animal",
    },
    {
      id: "bilateria",
      node: "билатерии",
      title: "Двустороннее тело",
      appearedMa: 560,
      level: "easy",
      novelty: "перед, зад, левая и правая сторона",
      effect: "животному удобнее двигаться вперед, искать еду и собирать органы чувств спереди",
      mainExamples: ["planarian", "earthworm", "lancelet"],
      marker: "bilateral",
    },
    {
      id: "hard-skeletons",
      node: "билатерии",
      title: "Панцири и скелеты",
      appearedMa: 540,
      level: "medium",
      novelty: "твердые защитные и опорные части тела",
      effect: "начинается гонка защиты, нападения и более сильного движения",
      mainExamples: ["nautilus", "slug", "horseshoeCrab"],
      marker: "exoskeleton",
    },
    {
      id: "protostomes",
      node: "первичноротые",
      title: "Первичноротые",
      appearedMa: 540,
      level: "medium",
      novelty: "один из двух больших планов развития билатерий",
      effect: "первичноротые дадут моллюсков, червей, членистоногих и большую часть животных видов",
      mainExamples: ["slug", "earthworm", "horseshoeCrab"],
      marker: "fork",
      filterTitle: "Первичноротые",
      filterOrder: 40,
      defaultScope: "all",
      flags: { filter: true },
    },
    {
      id: "mollusks",
      node: "моллюски",
      title: "Моллюски",
      appearedMa: 530,
      level: "easy",
      novelty: "мягкое тело, мускулистая нога и часто раковина",
      effect: "моллюски дают улиток, слизней, двустворок, осьминогов и наутилусов",
      mainExamples: ["slug", "octopus", "nautilus"],
      marker: "fork",
      filterTitle: "Моллюски",
    },
    {
      id: "cephalopods",
      node: "головоногие",
      title: "Головоногие",
      appearedMa: 500,
      level: "hard",
      novelty: "нога моллюска превращается в щупальца, а поведение усложняется",
      effect: "осьминоги, кальмары и наутилусы становятся активными морскими животными",
      mainExamples: ["octopus", "nautilus"],
      marker: "slug",
    },
    {
      id: "annelids",
      node: "кольчатые черви",
      title: "Кольчатые черви",
      appearedMa: 520,
      level: "medium",
      novelty: "тело из повторяющихся сегментов",
      effect: "сегменты помогают ползать, рыть и строить длинное гибкое тело",
      mainExamples: ["earthworm"],
      marker: "worm",
    },
    {
      id: "ecdysozoans",
      node: "линяющие",
      title: "Линяющие",
      appearedMa: 535,
      level: "medium",
      novelty: "тело растет рывками через сброс наружной оболочки",
      effect: "линька даст членистоногих, нематод и близкие ветки",
      mainExamples: ["spider", "crayfish", "silverfish"],
      marker: "molt",
    },
    {
      id: "panarthropods",
      node: "панартроподы",
      title: "Панартроподы",
      appearedMa: 525,
      level: "hard",
      novelty: "сегментированное тело с парными придатками",
      effect: "панартроподы ведут к членистоногим и их мягкотелым родственникам",
      mainExamples: ["horseshoeCrab", "spider", "springtail"],
      marker: "sixlegs",
    },
    {
      id: "arthropods",
      node: "членистоногие",
      title: "Членистоногие",
      appearedMa: 520,
      level: "easy",
      novelty: "наружный скелет и суставчатые ноги",
      effect: "тело хорошо защищено и удобно для ходьбы, плавания, хватания и полета",
      mainExamples: ["horseshoeCrab", "spider", "crayfish"],
      marker: "beetle",
      filterTitle: "Артроподы",
    },
    {
      id: "chelicerates",
      node: "хелицеровые",
      title: "Хелицеровые",
      appearedMa: 500,
      level: "medium",
      novelty: "нет усиков, первая пара придатков работает как хелицеры",
      effect: "хелицеровые дают пауков, скорпионов, клещей и мечехвостов",
      mainExamples: ["spider", "horseshoeCrab"],
      marker: "fork",
    },
    {
      id: "crustaceans",
      node: "ракообразные",
      title: "Ракообразные",
      appearedMa: 510,
      level: "medium",
      novelty: "водная членистоногая ветка с двумя парами усиков",
      effect: "ракообразные занимают множество морских и пресноводных ролей",
      mainExamples: ["crayfish"],
      marker: "fork",
    },
    {
      id: "hexapods",
      node: "шестиногие",
      title: "Шестиногие",
      appearedMa: 420,
      level: "medium",
      novelty: "тело с шестью ногами и жизнью среди почвы, растений и воздуха",
      effect: "шестиногие ведут к насекомым и их близким родственникам",
      mainExamples: ["springtail", "silverfish", "dragonfly"],
      marker: "sixlegs",
    },
    {
      id: "insects",
      node: "насекомые",
      title: "Насекомые",
      appearedMa: 410,
      level: "easy",
      novelty: "шесть ног, усики и компактное сухопутное тело",
      effect: "насекомые становятся одной из самых заметных и богатых видами веток суши",
      mainExamples: ["silverfish", "dragonfly", "grasshopper"],
      marker: "insect",
    },
    {
      id: "terrestrial-arthropods",
      node: "членистоногие",
      title: "Членистоногие на суше",
      appearedMa: 430,
      level: "medium",
      novelty: "панцирь удерживает воду, а ноги несут тело по суше",
      effect: "суша получает первых заметных ползающих животных задолго до крупных позвоночных",
      mainExamples: ["spider", "horseshoeCrab", "silverfish"],
      marker: "footprint",
    },
    {
      id: "winged-insects",
      node: "крылатые насекомые",
      title: "Крылатые насекомые",
      appearedMa: 400,
      level: "hard",
      novelty: "полет на крыльях",
      effect: "насекомые быстрее находят пищу, пары и новые места",
      mainExamples: ["dragonfly", "butterfly", "fly"],
      marker: "wing",
    },
    {
      id: "complete-metamorphosis",
      node: "насекомые",
      title: "Полное превращение",
      appearedMa: 350,
      level: "hard",
      novelty: "личинка и взрослое насекомое живут по-разному",
      effect: "дети и взрослые меньше конкурируют и могут использовать разные источники пищи",
      mainExamples: ["butterfly", "fly", "bee"],
      marker: "metamorphosis",
    },
    {
      id: "beetles",
      node: "жуки",
      title: "Жуки",
      appearedMa: 300,
      level: "hard",
      novelty: "передние крылья превращаются в твердые надкрылья",
      effect: "жуки получают защиту для тела и задних летательных крыльев",
      mainExamples: ["ladybird"],
      marker: "beetle",
    },
    {
      id: "hymenoptera",
      node: "перепончатокрылые",
      title: "Перепончатокрылые",
      appearedMa: 250,
      level: "hard",
      novelty: "тонкие перепончатые крылья и сложное поведение",
      effect: "перепончатокрылые дают пчел, ос, муравьев и множество общественных форм",
      mainExamples: ["bee", "ant", "wasp"],
      marker: "ant",
    },
    {
      id: "social-insects",
      node: "перепончатокрылые",
      title: "Общественные насекомые",
      appearedMa: 100,
      level: "hard",
      novelty: "колония с разделением работы",
      effect: "семья работает как большой организм: строит, ищет пищу и защищается вместе",
      mainExamples: ["ant", "bee", "wasp"],
      marker: "ant",
    },
    {
      id: "diptera",
      node: "двукрылые",
      title: "Двукрылые",
      appearedMa: 245,
      level: "hard",
      novelty: "одна пара крыльев и балансиры вместо второй пары",
      effect: "мухи и комары становятся быстрыми и маневренными летунами",
      mainExamples: ["fly", "mosquito"],
      marker: "mosquito",
    },
    {
      id: "lepidoptera",
      node: "чешуекрылые",
      title: "Чешуекрылые",
      appearedMa: 200,
      level: "hard",
      novelty: "крылья с чешуйками и личинка-гусеница",
      effect: "взрослые и личинки могут жить на разных ресурсах",
      mainExamples: ["butterfly"],
      marker: "butterfly",
    },
    {
      id: "deuterostomes",
      node: "вторичноротые",
      title: "Вторичноротые",
      appearedMa: 540,
      level: "medium",
      novelty: "другой план раннего развития зародыша",
      effect: "у вторичноротых появляются иглокожие, хордовые и позвоночные",
      mainExamples: ["starfish", "lancelet"],
      marker: "star",
      filterTitle: "Вторичноротые",
      filterOrder: 50,
      defaultScope: "detail",
      flags: { filter: true },
    },
    {
      id: "echinoderms",
      node: "иглокожие",
      title: "Иглокожие",
      appearedMa: 520,
      level: "hard",
      novelty: "водно-сосудистая система и необычная взрослая симметрия",
      effect: "морские звезды и ежи показывают соседнюю вторичноротую ветку без хорды",
      mainExamples: ["starfish", "seaUrchin"],
      marker: "star",
    },
    {
      id: "chordates",
      node: "хордовые",
      title: "Хорда",
      appearedMa: 530,
      level: "easy",
      novelty: "внутренняя упругая ось вдоль тела",
      effect: "хорда помогает строить плавание, движение и будущий позвоночник",
      mainExamples: ["lancelet", "lamprey", "perch"],
      marker: "chord",
      filterTitle: "Хордовые",
    },
    {
      id: "craniates",
      node: "черепные",
      title: "Череп",
      appearedMa: 520,
      level: "medium",
      novelty: "передний конец тела получает защиту для мозга и органов чувств",
      effect: "голова становится важным центром управления",
      mainExamples: ["lamprey", "perch"],
      marker: "skull",
    },
    {
      id: "jawless-vertebrates",
      node: "бесчелюстные",
      title: "Бесчелюстные",
      appearedMa: 500,
      level: "hard",
      novelty: "рот без челюстей, но уже есть черепная позвоночная организация",
      effect: "миноги показывают живую боковую ветку позвоночных до появления челюстей",
      mainExamples: ["lamprey"],
      marker: "skull",
    },
    {
      id: "jawed-vertebrates",
      node: "челюстноротые",
      title: "Челюсти",
      appearedMa: 430,
      level: "medium",
      novelty: "рот становится хватательным и кусательным",
      effect: "можно удерживать добычу и активнее питаться",
      mainExamples: ["dunkleosteus", "perch", "shark"],
      marker: "jaw",
    },
    {
      id: "cartilaginous-fishes",
      node: "хрящевые рыбы",
      title: "Хрящевые рыбы",
      appearedMa: 425,
      level: "hard",
      novelty: "легкий хрящевой скелет, сильные органы чувств и активное плавание",
      effect: "хрящевые рыбы дают акул, скатов и химер как живую боковую ветку челюстноротых",
      mainExamples: ["shark"],
      marker: "fin",
    },
    {
      id: "bony-vertebrates",
      node: "костные позвоночные",
      title: "Костная линия",
      appearedMa: 425,
      level: "easy",
      novelty: "внутри тела становится много прочной кости",
      effect: "позвоночные получают прочную опору; отсюда пойдут большинство рыб и наземные животные",
      mainExamples: ["perch", "coelacanth", "frog"],
      marker: "bone",
    },
    {
      id: "ray-finned-fishes",
      node: "лучеперые",
      title: "Лучеперые рыбы",
      appearedMa: 420,
      level: "medium",
      novelty: "плавники держатся на тонких лучах",
      effect: "лучеперые становятся самой богатой видами рыбной линией современных водоемов",
      mainExamples: ["perch"],
      marker: "fin",
    },
    {
      id: "lobe-fins",
      node: "лопастеперые",
      title: "Лопастные плавники",
      appearedMa: 400,
      level: "hard",
      novelty: "плавники с внутренними костями",
      effect: "лопастные плавники станут основой для конечностей",
      mainExamples: ["coelacanth", "lungfish", "tiktaalik"],
      marker: "fin",
    },
    {
      id: "tetrapods",
      node: "четвероногие",
      title: "Конечности",
      appearedMa: 375,
      level: "easy",
      novelty: "четыре опорные конечности вместо одних плавников",
      effect: "позвоночные получают путь к мелководью и суше",
      mainExamples: ["tiktaalik", "frog", "lizard"],
      marker: "limb",
    },
    {
      id: "amphibians",
      node: "амфибии",
      title: "Амфибии",
      appearedMa: 370,
      level: "medium",
      novelty: "четвероногая жизнь, сильно связанная с водой и влажной кожей",
      effect: "амфибии занимают границу воды и суши",
      mainExamples: ["frog", "axolotl"],
      marker: "limb",
    },
    {
      id: "amniotes",
      node: "амниоты",
      title: "Амниотическое яйцо",
      appearedMa: 320,
      level: "easy",
      novelty: "зародыш развивается в защитных оболочках",
      effect: "размножение меньше зависит от воды",
      mainExamples: ["lizard", "sparrow", "mouse"],
      marker: "egg",
    },
    {
      id: "synapsids",
      node: "синапсиды",
      title: "Синапсидный череп",
      appearedMa: 315,
      level: "easy",
      novelty: "одно височное окно за глазом",
      effect: "синапсиды получают новые места крепления челюстных мышц и ведут к млекопитающим",
      mainExamples: ["dimetrodon", "mouse", "human"],
      marker: "split",
      filterTitle: "Синапсиды",
      filterOrder: 70,
      defaultScope: "all",
      flags: { filter: true },
    },
    {
      id: "sauropsids",
      node: "завропсиды",
      title: "Завропсидная сторона амниот",
      appearedMa: 315,
      level: "easy",
      novelty: "другая большая амниотическая дорога",
      effect: "завропсиды дадут ящериц, змей, крокодилов, динозавров и птиц",
      mainExamples: ["lizard", "crocodile", "sparrow"],
      marker: "split",
      filterTitle: "Диапсиды",
      filterOrder: 60,
      defaultScope: "all",
      flags: { filter: true },
    },
    {
      id: "diapsid-skull",
      node: "завропсиды",
      title: "Диапсидные окна",
      appearedMa: 295,
      level: "medium",
      novelty: "два височных окна за глазом",
      effect: "череп становится легче, а челюстные мышцы получают удобные места крепления",
      mainExamples: ["lizard", "crocodile", "sparrow"],
      marker: "skull",
    },
    {
      id: "therapsids",
      node: "терапсиды",
      title: "Терапсиды",
      appearedMa: 295,
      level: "medium",
      novelty: "синапсиды становятся более активными, зубы и стойка усложняются",
      effect: "терапсиды ведут от ранних синапсидов к цинодонтам и млекопитающим",
      mainExamples: ["gorgonops", "thrinaxodon", "morganucodon"],
      marker: "mammal",
    },
    {
      id: "cynodonts",
      node: "цинодонты",
      title: "Цинодонты",
      appearedMa: 270,
      level: "hard",
      novelty: "точнее жевание, разные зубы и более млекопитающая челюсть",
      effect: "питание становится эффективнее, а линия приближается к млекопитающим",
      mainExamples: ["thrinaxodon", "morganucodon", "human"],
      marker: "jaw",
    },
    {
      id: "mammaliaforms",
      node: "млекопитающие формы",
      title: "Млекопитающие формы",
      appearedMa: 235,
      level: "hard",
      novelty: "задние кости челюсти уменьшаются и переходят к слуху",
      effect: "челюсть и ухо разделяют работу, а слух становится тоньше",
      mainExamples: ["morganucodon", "mouse"],
      marker: "mammal",
    },
    {
      id: "mammals",
      node: "млекопитающие",
      title: "Млекопитающие",
      appearedMa: 220,
      level: "easy",
      novelty: "шерсть, молоко и более теплое тело",
      effect: "детенышей проще кормить и защищать, а маленькое ночное тело получает преимущество",
      mainExamples: ["morganucodon", "mouse", "bat"],
      marker: "mammal",
    },
    {
      id: "monotremes",
      node: "однопроходные",
      title: "Однопроходные",
      appearedMa: 170,
      level: "medium",
      novelty: "млекопитающие, которые сохраняют яйцекладку",
      effect: "утконос и ехидна показывают древнюю сторону разнообразия млекопитающих",
      mainExamples: ["platypus", "echidna"],
      marker: "egg",
    },
    {
      id: "therians",
      node: "звери",
      title: "Звери",
      appearedMa: 170,
      level: "medium",
      novelty: "детеныш развивается в теле матери",
      effect: "звери дают сумчатых и плацентарных",
      mainExamples: ["kangaroo", "mouse", "human"],
      marker: "mammal",
    },
    {
      id: "marsupials",
      node: "сумчатые",
      title: "Сумчатые",
      appearedMa: 125,
      level: "medium",
      novelty: "детеныш рождается очень рано и доразвивается у матери",
      effect: "сумчатые занимают множество ролей, особенно в Австралии и Америке",
      mainExamples: ["kangaroo", "koala"],
      marker: "mammal",
    },
    {
      id: "placentals",
      node: "плацентарные",
      title: "Плацентарные",
      appearedMa: 160,
      level: "easy",
      novelty: "долгое питание детеныша через плаценту",
      effect: "детеныш может дольше развиваться внутри тела и рождаться более подготовленным",
      mainExamples: ["mouse", "rabbit", "human"],
      marker: "mammal",
    },
    {
      id: "laurasiatherians",
      node: "лавразиотерии",
      title: "Лавразиотерии",
      appearedMa: 85,
      level: "hard",
      novelty: "крупная плацентарная ветка с очень разными телами",
      effect: "лавразиотерии дают летучих мышей, китов, копытных, хищных и их родственников",
      mainExamples: ["bat", "whale"],
      marker: "mammal",
    },
    {
      id: "archosaurs",
      node: "архозавры",
      title: "Архозавры",
      appearedMa: 250,
      level: "medium",
      novelty: "более активная стойка и шаг",
      effect: "архозавры дадут крокодилов, птерозавров, динозавров и птиц",
      mainExamples: ["crocodile", "pteranodon", "sparrow"],
      marker: "dino",
    },
    {
      id: "lepidosaurs",
      node: "лепидозавры",
      title: "Лепидозавры",
      appearedMa: 240,
      level: "medium",
      novelty: "завропсидная ветка ящериц, змей и гаттерии",
      effect: "лепидозавры становятся очень заметными среди современных рептилий",
      mainExamples: ["tuatara", "lizard", "snake"],
      marker: "fork",
    },
    {
      id: "squamates",
      node: "чешуйчатые",
      title: "Чешуйчатые",
      appearedMa: 190,
      level: "hard",
      novelty: "подвижный череп и чешуйчатое тело у ящериц и змей",
      effect: "ящерицы и змеи занимают множество наземных, древесных и водных ниш",
      mainExamples: ["lizard", "snake"],
      marker: "fork",
    },
    {
      id: "pseudosuchians",
      node: "псевдозухии",
      title: "Крокодилья сторона архозавров",
      appearedMa: 250,
      level: "medium",
      novelty: "архозавровая ветка к крокодилам и их древним родственникам",
      effect: "полуводные хищники переживают кризисы и остаются рядом с птицами как родственники",
      mainExamples: ["prestosuchus", "crocodile", "alligator"],
      marker: "fork",
    },
    {
      id: "crocodilians",
      node: "крокодилы",
      title: "Крокодилы",
      appearedMa: 95,
      level: "hard",
      novelty: "полуводное тело, сильные челюсти и скрытная охота",
      effect: "крокодилья линия переживает кризисы и остается живой веткой архозавров",
      mainExamples: ["crocodile", "alligator"],
      marker: "jaw",
    },
    {
      id: "avemetatarsalians",
      node: "авеметатарзалии",
      title: "Авеметатарзалии",
      appearedMa: 250,
      level: "hard",
      novelty: "задние конечности и стопа лучше подходят для быстрого движения",
      effect: "авеметатарзалии дают птерозавров, динозавров и птиц",
      mainExamples: ["pteranodon", "herrerasaurus", "sparrow"],
      marker: "footprint",
    },
    {
      id: "pterosaurs",
      node: "птерозавры",
      title: "Птерозавры",
      appearedMa: 228,
      level: "medium",
      novelty: "крыло из кожи на удлиненном пальце",
      effect: "позвоночные впервые становятся активными летунами",
      mainExamples: ["pteranodon"],
      marker: "bird",
    },
    {
      id: "dinosauromorphs",
      node: "авеметатарзалии",
      title: "Динозавроморфы",
      appearedMa: 245,
      level: "hard",
      novelty: "легкое тело, длинные задние ноги и быстрый бег",
      effect: "рядом с птерозаврами формируется линия к динозаврам",
      mainExamples: ["herrerasaurus", "triceratops", "sparrow"],
      marker: "dino",
    },
    {
      id: "dinosaurs",
      node: "динозавры",
      title: "Динозавры",
      appearedMa: 235,
      level: "easy",
      novelty: "ноги стоят под телом",
      effect: "ходьба становится мощной и экономной; динозавры занимают множество наземных ролей",
      mainExamples: ["herrerasaurus", "triceratops", "sparrow"],
      marker: "dino",
      filterTitle: "Динозавры",
    },
    {
      id: "saurischians",
      node: "ящеротазовые",
      title: "Ящеротазовые",
      appearedMa: 230,
      level: "hard",
      novelty: "одна из двух больших динозавровых дорог",
      effect: "ящеротазовые расходятся на завроподоморфов и тероподов, а тероподы позже дадут птиц",
      mainExamples: ["apatosaurus", "allosaurus", "sparrow"],
      marker: "dino",
    },
    {
      id: "theropods",
      node: "тероподы",
      title: "Тероподы",
      appearedMa: 230,
      level: "medium",
      novelty: "двуногие хищные динозавры с активным движением",
      effect: "тероподы постепенно дают линию птиц",
      mainExamples: ["allosaurus", "velociraptor", "sparrow"],
      marker: "dino",
    },
    {
      id: "coelurosaurs",
      node: "целурозавры",
      title: "Целурозавры",
      appearedMa: 170,
      level: "hard",
      novelty: "легкий скелет, перья и активное поведение становятся важнее",
      effect: "целурозавры включают тираннозавроидов, дромеозавров и птичью линию",
      mainExamples: ["tyrannosaurus", "velociraptor", "archaeopteryx"],
      marker: "bird",
    },
    {
      id: "theropod-feathers",
      node: "тероподы",
      title: "Перья у теропод",
      appearedMa: 170,
      level: "hard",
      novelty: "перья сначала работают как покров, сигнал и теплоизоляция",
      effect: "готовая перьевая конструкция позже становится частью птичьего крыла",
      mainExamples: ["velociraptor", "archaeopteryx", "sparrow"],
      marker: "bird",
    },
    {
      id: "avialans",
      node: "авиалы",
      title: "Птичья линия",
      appearedMa: 160,
      level: "hard",
      novelty: "крылья, маховые перья и легкий скелет работают вместе",
      effect: "тероподовая линия переходит к настоящему активному полету",
      mainExamples: ["archaeopteryx", "sparrow"],
      marker: "bird",
    },
    {
      id: "birds",
      node: "птицы",
      title: "Птицы",
      appearedMa: 150,
      level: "easy",
      novelty: "перья и крылья в птичьей линии динозавров",
      effect: "полет и теплоизоляция открывают новую жизнь в воздухе",
      mainExamples: ["archaeopteryx", "sparrow", "raven"],
      marker: "bird",
    },
    {
      id: "modern-birds",
      node: "птицы",
      title: "Современные птицы",
      appearedMa: 100,
      level: "medium",
      novelty: "клюв, короткий хвост и легкое тело",
      effect: "птицы становятся разнообразными летающими, плавающими и бегающими динозаврами",
      mainExamples: ["sparrow", "raven"],
      marker: "bird",
    },
    {
      id: "primates",
      node: "приматы",
      title: "Приматы",
      appearedMa: 55,
      level: "easy",
      novelty: "цепкие руки, глаза вперед и обучение",
      effect: "жизнь на ветках становится удобнее, а поведение сложнее",
      mainExamples: ["lemur", "macaque", "human"],
      marker: "ape",
      filterTitle: "Приматы",
    },
    {
      id: "rodents",
      node: "грызуны",
      title: "Грызуны",
      appearedMa: 60,
      level: "medium",
      novelty: "постоянно растущие резцы для грызения",
      effect: "грызуны становятся одной из самых успешных веток плацентарных",
      mainExamples: ["mouse", "squirrel", "nakedMoleRat"],
      marker: "mammal",
    },
    {
      id: "bats",
      node: "рукокрылые",
      title: "Летучие мыши",
      appearedMa: 55,
      level: "hard",
      novelty: "крыло из кожи между пальцами",
      effect: "млекопитающие занимают ночной воздух и охоту в полете",
      mainExamples: ["bat"],
      marker: "bird",
    },
    {
      id: "whales",
      node: "китообразные",
      title: "Киты уходят в море",
      appearedMa: 50,
      level: "hard",
      novelty: "млекопитающее тело снова становится водным",
      effect: "теплокровность, дыхание воздухом и живорождение начинают работать в океане",
      mainExamples: ["whale"],
      marker: "ocean",
    },
    {
      id: "monkeys",
      node: "обезьяны",
      title: "Обезьяны",
      appearedMa: 40,
      level: "medium",
      novelty: "дневное зрение, хватание и сложная социальная жизнь",
      effect: "приматы становятся активными древесными и наземными животными",
      mainExamples: ["macaque", "baboon", "human"],
      marker: "monkey",
    },
    {
      id: "catarrhines",
      node: "узконосые обезьяны",
      title: "Узконосые обезьяны",
      appearedMa: 30,
      level: "hard",
      novelty: "ветка обезьян Старого Света и человекообразных",
      effect: "рядом расходятся макаки, павианы, гиббоны, большие человекообразные и наша линия",
      mainExamples: ["macaque", "baboon", "human"],
      marker: "monkey",
    },
    {
      id: "apes",
      node: "человекообразные",
      title: "Человекообразные",
      appearedMa: 20,
      level: "medium",
      novelty: "нет хвоста, гибкие плечи и крупный мозг",
      effect: "руки становятся особенно важны для лазания, хватания и обучения",
      mainExamples: ["orangutan", "chimpanzee", "human"],
      marker: "ape",
    },
    {
      id: "late-apes",
      node: "человекообразные",
      title: "Поздние человекообразные",
      appearedMa: 10,
      level: "hard",
      novelty: "крупные человекообразные живут в меняющемся мире лесов и открытых пространств",
      effect: "руки, плечи, обучение и социальность остаются важным фоном для будущей человеческой линии",
      mainExamples: ["chimpanzee", "orangutan", "human"],
      marker: "ape",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "hominins",
      node: "люди",
      title: "Прямохождение",
      appearedMa: 6,
      level: "easy",
      novelty: "наша линия все чаще ходит на двух ногах",
      effect: "руки освобождаются, обзор над травой становится лучше, переносить еду и детенышей удобнее",
      mainExamples: ["human"],
      image: "assets/photos/homo-erectus.jpg",
      imageLabel: "пример: прямоходящая человеческая линия",
      marker: "footprint",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "early-homo",
      node: "люди",
      title: "Ранние Homo",
      appearedMa: 2,
      level: "hard",
      novelty: "мозг, руки и орудия становятся устойчивой частью человеческой линии",
      effect: "поведение начинает сильнее зависеть от обучения и сделанных предметов",
      mainExamples: ["human"],
      image: "assets/photos/log-stone-tool.jpg",
      imageLabel: "пример: древнее каменное орудие",
      marker: "handaxe",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "homo-erectus",
      node: "люди",
      title: "Homo erectus",
      appearedMa: 1.8,
      level: "hard",
      novelty: "более дальние переходы, устойчивые навыки и тело для долгой ходьбы",
      effect: "человеческая линия расселяется шире и дольше удерживает традиции изготовления орудий",
      mainExamples: ["human"],
      image: "assets/photos/homo-erectus.jpg",
      imageLabel: "пример: Homo erectus",
      marker: "migration",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "stone-tools",
      node: "люди",
      title: "Каменные орудия",
      appearedMa: 3.3,
      level: "medium",
      novelty: "предмет специально меняют под задачу",
      effect: "руки, мозг и обучение начинают сильнее менять поведение нашей линии",
      mainExamples: ["human"],
      image: "assets/photos/log-stone-tool.jpg",
      imageLabel: "пример: древнее каменное орудие",
      marker: "handaxe",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "controlled-fire",
      node: "люди",
      title: "Управление огнем",
      appearedMa: 1,
      level: "medium",
      novelty: "огонь становится частью жизни людей",
      effect: "тепло, свет, защита и приготовление пищи меняют стоянки и общение",
      mainExamples: ["human"],
      image: "assets/photos/fire-cave.svg",
      imageLabel: "пример: костер в пещере",
      marker: "torch",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "humans",
      node: "люди",
      title: "Homo sapiens",
      appearedMa: 0.3,
      level: "easy",
      novelty: "наш вид и очень сильная культурная передача",
      effect: "обучение и речь меняют жизнь быстрее, чем большинство биологических процессов",
      mainExamples: ["human"],
      marker: "child",
      filterTitle: "Человек",
      filterOrder: 80,
      defaultScope: "all",
      flags: { filter: true, focusOnly: ["humans"] },
    },
    {
      id: "sapiens-expansion",
      node: "люди",
      title: "Homo sapiens распространяется",
      appearedMa: 0.15,
      level: "hard",
      novelty: "наш вид становится все заметнее и готовится к дальним расселениям",
      effect: "человеческая история превращается в сеть групп, встреч и обменов",
      mainExamples: ["human"],
      image: "assets/photos/human.jpg",
      imageLabel: "наш вид: Homo sapiens",
      marker: "human",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "migration",
      node: "люди",
      title: "Люди расселяются",
      appearedMa: 0.07,
      level: "hard",
      novelty: "Homo sapiens выходит в новые регионы",
      effect: "культура помогает жить в пустынях, лесах, холоде и на побережьях",
      mainExamples: ["human"],
      image: "assets/photos/log-stone-tool.jpg",
      imageLabel: "орудия и следы расселения",
      marker: "migration",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "symbolic-art",
      node: "люди",
      title: "Символы и искусство",
      appearedMa: 0.04,
      level: "hard",
      novelty: "рисунки, украшения и знаки",
      effect: "память группы становится видимой и может передаваться через предметы и изображения",
      mainExamples: ["human"],
      image: "assets/photos/log-lascaux.jpg",
      imageLabel: "пример: пещерное искусство",
      marker: "paint",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "late-ice-age",
      node: "люди",
      title: "Конец ледникового мира",
      appearedMa: 0.02,
      level: "hard",
      novelty: "после ледникового максимума климат и ландшафты быстро меняются",
      effect: "люди перестраивают маршруты, стоянки и пищевые привычки под новый мир",
      mainExamples: ["human"],
      image: "assets/photos/ice-age.svg",
      imageLabel: "природный мир после ледникового максимума",
      marker: "climate",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "agriculture",
      node: "люди",
      title: "Земледелие",
      appearedMa: 0.012,
      level: "easy",
      novelty: "люди выращивают растения и меняют ландшафт",
      effect: "пища планируется заранее; появляются поселения, запасы и новые общества",
      mainExamples: ["human", "grass"],
      image: "assets/photos/log-wheat.jpg",
      imageLabel: "пример: зерно и выращивание растений",
      marker: "grain",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "writing-cities",
      node: "люди",
      title: "Письмо и города",
      appearedMa: 0.005,
      level: "medium",
      novelty: "память общества записывается вне головы человека",
      effect: "счета, законы, маршруты и знания начинают переживать отдельную жизнь человека",
      mainExamples: ["human"],
      image: "assets/photos/log-manuscript.jpg",
      imageLabel: "пример: письменная память",
      marker: "book",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "ancient-states",
      node: "люди",
      title: "Античные государства",
      appearedMa: 0.0025,
      level: "hard",
      novelty: "дороги, монеты, письменные традиции и города связывают большие территории",
      effect: "знания, товары и болезни распространяются по длинным маршрутам",
      mainExamples: ["human"],
      image: "assets/photos/log-medieval-city.jpg",
      imageLabel: "город и письменная культура",
      marker: "empire",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "medieval-world",
      node: "люди",
      title: "Средневековый мир",
      appearedMa: 0.0015,
      level: "hard",
      novelty: "города, рукописи, корабли, ремесла и земледельческие общества",
      effect: "традиции и знания удерживаются книгами, мастерскими и институтами",
      mainExamples: ["human"],
      image: "assets/photos/log-manuscript.jpg",
      imageLabel: "рукописи и книжная культура",
      marker: "book",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "printing",
      node: "люди",
      title: "Книгопечатание",
      appearedMa: 0.00055,
      level: "hard",
      novelty: "текст быстро копируется в большом числе одинаковых экземпляров",
      effect: "идеи, инструкции и споры распространяются быстрее рукописного мира",
      mainExamples: ["human"],
      image: "assets/photos/log-printing-press.jpg",
      imageLabel: "пример: печатный станок",
      marker: "print",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "scientific-revolution",
      node: "люди",
      title: "Научная революция",
      appearedMa: 0.0004,
      level: "hard",
      novelty: "эксперимент, математика и печатные сети ускоряют проверку знаний",
      effect: "техника и понимание природы начинают расти быстрее прежних традиций",
      mainExamples: ["human"],
      image: "assets/photos/log-printing-press.jpg",
      imageLabel: "печатные знания и новые методы",
      marker: "print",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "industrialization",
      node: "люди",
      title: "Индустриальный рывок",
      appearedMa: 0.00025,
      level: "medium",
      novelty: "машины и ископаемое топливо резко усиливают работу людей",
      effect: "производство, транспорт и города растут быстрее, а влияние человека на природу усиливается",
      mainExamples: ["human"],
      image: "assets/photos/log-steam-engine.jpg",
      imageLabel: "пример: паровая машина",
      marker: "factory",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "electric-world",
      node: "люди",
      title: "Электрический мир",
      appearedMa: 0.00013,
      level: "medium",
      novelty: "электричество, радио, автомобили и самолеты меняют быт и связь",
      effect: "энергия и сообщения начинают проходить большие расстояния очень быстро",
      mainExamples: ["human"],
      image: "assets/photos/log-radio.jpg",
      imageLabel: "пример: радиоприемник",
      marker: "radio",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "computers",
      node: "люди",
      title: "Компьютеры",
      appearedMa: 0.000064,
      level: "medium",
      novelty: "вычисления становятся машинной работой",
      effect: "данные, расчеты, медицина, космос и управление системами резко ускоряются",
      mainExamples: ["human"],
      image: "assets/photos/log-computer.jpg",
      imageLabel: "пример: электронный компьютер",
      marker: "computer",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "internet",
      node: "люди",
      title: "Интернет",
      appearedMa: 0.000032,
      level: "easy",
      novelty: "люди и компьютеры связываются в глобальную сеть",
      effect: "поиск, общение и обучение перестают быть привязаны к одному месту",
      mainExamples: ["human"],
      image: "assets/photos/network-globe.svg",
      imageLabel: "пример: глобальная цифровая сеть",
      marker: "network",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "smartphones",
      node: "люди",
      title: "Смартфоны",
      appearedMa: 0.000016,
      level: "easy",
      novelty: "карманный компьютер с камерой, картой, связью и памятью",
      effect: "цифровая память и связь становятся постоянной частью повседневности",
      mainExamples: ["human"],
      image: "assets/photos/log-smartphone.jpg",
      imageLabel: "пример: смартфон",
      marker: "phone",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "cloud-culture",
      node: "люди",
      title: "Облачная цифровая культура",
      appearedMa: 0.000008,
      level: "hard",
      novelty: "видео, игры, обучение и работа уходят в постоянно доступные онлайн-сервисы",
      effect: "культура меняется быстрее, чем большинство биологических процессов",
      mainExamples: ["human"],
      image: "assets/photos/log-smartphone.jpg",
      imageLabel: "постоянная связь и облачные сервисы",
      marker: "cloud",
      flags: { focusOnly: ["humans"] },
    },
    {
      id: "generative-ai",
      node: "люди",
      title: "Генеративный AI",
      appearedMa: 0.000004,
      level: "easy",
      novelty: "цифровые помощники создают текст, код, изображения и объяснения",
      effect: "внешняя память получает собеседника: можно спрашивать, пробовать и быстро получать черновик",
      mainExamples: ["human"],
      image: "assets/photos/log-computer.jpg",
      imageLabel: "компьютер как основа цифровых помощников",
      marker: "ai",
      flags: { focusOnly: ["humans"] },
    },
  ],
};
