window.EVOL_GAMES = {
  levels: [
    { id: "easy", title: "легкий" },
    { id: "medium", title: "средний" },
    { id: "hard", title: "сложный" },
  ],

  target: "human",

  timelineEras: [
    { id: "archean", label: "архей", startMa: 4000, endMa: 2500 },
    { id: "proterozoic", label: "протерозой", startMa: 2500, endMa: 541 },
    { id: "paleozoic", label: "палеозой", startMa: 541, endMa: 252 },
    { id: "mesozoic", label: "мезозой", startMa: 252, endMa: 66 },
    { id: "cenozoic", label: "кайнозой", startMa: 66, endMa: 0 },
  ],

  timelinePeriods: [
    { id: "early-archean", parentId: "archean", label: "ранний архей", startMa: 4000, endMa: 3200 },
    { id: "late-archean", parentId: "archean", label: "поздний архей", startMa: 3200, endMa: 2500 },
    { id: "early-proterozoic", parentId: "proterozoic", label: "ранний протерозой", startMa: 2500, endMa: 1600 },
    { id: "middle-proterozoic", parentId: "proterozoic", label: "средний протерозой", startMa: 1600, endMa: 1000 },
    { id: "late-proterozoic", parentId: "proterozoic", label: "поздний протерозой", startMa: 1000, endMa: 720 },
    { id: "cryogenian", parentId: "proterozoic", label: "криогений", startMa: 720, endMa: 635 },
    { id: "ediacaran", parentId: "proterozoic", label: "эдиакарий", startMa: 635, endMa: 541 },
    { id: "cambrian", parentId: "paleozoic", label: "кембрий", startMa: 541, endMa: 485 },
    { id: "ordovician", parentId: "paleozoic", label: "ордовик", startMa: 485, endMa: 444 },
    { id: "silurian", parentId: "paleozoic", label: "силур", startMa: 444, endMa: 419 },
    { id: "devonian", parentId: "paleozoic", label: "девон", startMa: 419, endMa: 359 },
    { id: "carboniferous", parentId: "paleozoic", label: "карбон", startMa: 359, endMa: 299 },
    { id: "permian", parentId: "paleozoic", label: "пермь", startMa: 299, endMa: 252 },
    { id: "triassic", parentId: "mesozoic", label: "триас", startMa: 252, endMa: 201 },
    { id: "jurassic", parentId: "mesozoic", label: "юра", startMa: 201, endMa: 145 },
    { id: "cretaceous", parentId: "mesozoic", label: "мел", startMa: 145, endMa: 66 },
    { id: "paleogene", parentId: "cenozoic", label: "палеоген", startMa: 66, endMa: 23 },
    { id: "neogene", parentId: "cenozoic", label: "неоген", startMa: 23, endMa: 2.6 },
    { id: "quaternary", parentId: "cenozoic", label: "четвертичный", startMa: 2.6, endMa: 0 },
  ],

  timelineEvents: [
    {
      id: "prokaryotic-cells",
      title: "первые клетки",
      image: "assets/photos/bacteria.jpg",
      timeMa: 3800,
      eraId: "archean",
      periodId: "early-archean",
      novelty: "клетка с оболочкой и обменом веществ",
      gave: "жизнь стала отдельной маленькой системой, которая умеет питаться и копировать себя",
    },
    {
      id: "photosynthesis",
      title: "фотосинтез",
      image: "assets/photos/log-stromatolites.jpg",
      timeMa: 3400,
      eraId: "archean",
      periodId: "early-archean",
      novelty: "энергия света превращается в пищу",
      gave: "жизнь получила огромный источник энергии, а позже в атмосфере накопился кислород",
    },
    {
      id: "oxygen-revolution",
      title: "кислородная революция",
      image: "assets/photos/log-stromatolites.jpg",
      timeMa: 2400,
      eraId: "proterozoic",
      periodId: "early-proterozoic",
      novelty: "кислород накапливается в океане и атмосфере",
      gave: "мир стал химически другим: часть микробов погибла, зато позже появилось мощное кислородное дыхание",
    },
    {
      id: "eukaryotic-cell",
      title: "клетка с ядром",
      image: "assets/photos/amoeba.jpg",
      timeMa: 2000,
      eraId: "proterozoic",
      periodId: "early-proterozoic",
      novelty: "ядро и органеллы внутри клетки",
      gave: "клетки стали крупнее и сложнее, внутри появились рабочие отделы",
    },
    {
      id: "mitochondria",
      title: "митохондрии",
      image: "assets/photos/amoeba.jpg",
      timeMa: 1900,
      eraId: "proterozoic",
      periodId: "early-proterozoic",
      novelty: "внутри клетки появляется энергетический симбионт",
      gave: "эукариотическая клетка получила больше энергии для крупного и сложного тела",
    },
    {
      id: "chloroplasts",
      title: "хлоропласты",
      image: "assets/photos/plant-chlorophyte.jpg",
      timeMa: 1600,
      eraId: "proterozoic",
      periodId: "middle-proterozoic",
      novelty: "фотосинтезирующая бактерия становится частью клетки",
      gave: "началась большая линия водорослей и растений, которые сами делают пищу из света",
    },
    {
      id: "sexual-reproduction",
      title: "половое размножение",
      image: "assets/photos/plant-green-algae.jpg",
      timeMa: 1200,
      eraId: "proterozoic",
      periodId: "middle-proterozoic",
      novelty: "смешивание генов двух родителей",
      gave: "потомки стали разнообразнее, а отбор получил больше вариантов для эволюции",
    },
    {
      id: "multicellular-algae",
      title: "крупные водоросли",
      image: "assets/photos/plant-chara.jpg",
      timeMa: 1000,
      eraId: "proterozoic",
      periodId: "late-proterozoic",
      novelty: "многоклеточное тело у водорослей",
      gave: "клетки начали держаться вместе и строить более заметные водные тела",
    },
    {
      id: "multicellular-animals",
      title: "многоклеточные животные",
      image: "assets/photos/sponge.jpg",
      timeMa: 650,
      eraId: "proterozoic",
      periodId: "cryogenian",
      novelty: "много клеток работают как одно тело",
      gave: "можно стало строить ткани, форму тела и разделять работу между клетками",
    },
    {
      id: "nervous-system",
      title: "нервная система",
      image: "assets/photos/jellyfish.jpg",
      timeMa: 580,
      eraId: "proterozoic",
      periodId: "ediacaran",
      novelty: "нервные клетки связывают тело",
      gave: "животное стало быстрее отвечать на свет, прикосновение, добычу и опасность",
    },
    {
      id: "bilateria",
      title: "двустороннее тело",
      image: "assets/photos/planarian.jpg",
      timeMa: 560,
      eraId: "proterozoic",
      periodId: "ediacaran",
      novelty: "перед, зад, левая и правая сторона",
      gave: "животное стало удобнее направлять вперед: искать еду, ползти и чувствовать дорогу",
    },
    {
      id: "hard-skeletons",
      title: "панцири и скелеты",
      image: "assets/photos/nautilus.jpg",
      timeMa: 540,
      eraId: "paleozoic",
      periodId: "cambrian",
      novelty: "твердые наружные и внутренние опоры",
      gave: "животные получили защиту, рычаги для движения и более заметную летопись окаменелостей",
    },
    {
      id: "chordates",
      title: "хордовые",
      image: "assets/photos/lancelet.jpg",
      timeMa: 530,
      eraId: "paleozoic",
      periodId: "cambrian",
      novelty: "хорда и нервная трубка вдоль тела",
      gave: "появилась внутренняя ось тела, от которой позже пошли позвоночные",
    },
    {
      id: "arthropods",
      title: "членистоногие",
      image: "assets/photos/horseshoe-crab.jpg",
      timeMa: 520,
      eraId: "paleozoic",
      periodId: "cambrian",
      novelty: "наружный скелет и суставчатые ноги",
      gave: "тело стало хорошо защищенным и удобным для ходьбы, плавания и хватания",
    },
    {
      id: "vertebrate-skull",
      title: "череп",
      image: "assets/photos/lamprey.jpg",
      timeMa: 520,
      eraId: "paleozoic",
      periodId: "cambrian",
      novelty: "голова получает защитную коробку",
      gave: "мозг и органы чувств стали лучше защищены",
    },
    {
      id: "land-plants",
      title: "растения на суше",
      image: "assets/photos/plant-moss.jpg",
      timeMa: 470,
      eraId: "paleozoic",
      periodId: "ordovician",
      novelty: "защита от высыхания и споры",
      gave: "растения начали жить вне воды и постепенно готовить почвы для наземных экосистем",
    },
    {
      id: "terrestrial-arthropods",
      title: "членистоногие на суше",
      image: "assets/photos/local-spider.jpg",
      timeMa: 430,
      eraId: "paleozoic",
      periodId: "silurian",
      novelty: "маленькие ноги и покров работают на воздухе",
      gave: "животные начали активно осваивать сушу раньше крупных позвоночных",
    },
    {
      id: "jaws",
      title: "челюсти",
      image: "assets/photos/dunkleosteus-jaw.jpg",
      timeMa: 430,
      eraId: "paleozoic",
      periodId: "silurian",
      novelty: "подвижные челюсти",
      gave: "можно хватать крупную добычу и активнее питаться",
    },
    {
      id: "bony-vertebrates",
      title: "костный скелет",
      image: "assets/photos/local-perch.jpg",
      timeMa: 425,
      eraId: "paleozoic",
      periodId: "silurian",
      novelty: "внутри тела становится много прочной кости",
      gave: "позвоночные получили прочную опору, а позже эта линия дала большинство рыб и наземных животных",
    },
    {
      id: "vascular-plants",
      title: "сосуды растений",
      image: "assets/photos/plant-horsetail.jpg",
      timeMa: 420,
      eraId: "paleozoic",
      periodId: "silurian",
      novelty: "трубки для воды и питания",
      gave: "растения смогли расти выше и дальше уходить от воды",
    },
    {
      id: "insects",
      title: "насекомые",
      image: "assets/photos/arthropod-silverfish.jpg",
      timeMa: 410,
      eraId: "paleozoic",
      periodId: "devonian",
      novelty: "маленькое тело с шестью ногами",
      gave: "на суше появилась очень успешная линия мелких членистоногих",
    },
    {
      id: "lobe-fins",
      title: "лопастные плавники",
      image: "assets/photos/coelacanth.jpg",
      timeMa: 400,
      eraId: "paleozoic",
      periodId: "devonian",
      novelty: "плавники с внутренними костями",
      gave: "у позвоночных появилась будущая основа для конечностей",
    },
    {
      id: "insect-wings",
      title: "крылья насекомых",
      image: "assets/photos/arthropod-dragonfly.jpg",
      timeMa: 400,
      eraId: "paleozoic",
      periodId: "devonian",
      novelty: "полет на крыльях у насекомых",
      gave: "можно быстрее искать пищу, пары и новые места",
    },
    {
      id: "tetrapod-limbs",
      title: "конечности",
      image: "assets/photos/tiktaalik.jpg",
      timeMa: 375,
      eraId: "paleozoic",
      periodId: "devonian",
      novelty: "плавники превращаются в опорные конечности",
      gave: "позвоночные получили путь к мелководью и суше",
    },
    {
      id: "seeds",
      title: "семена",
      image: "assets/photos/plant-pine-cone.jpg",
      timeMa: 355,
      eraId: "paleozoic",
      periodId: "carboniferous",
      novelty: "зародыш с запасом пищи и защитной оболочкой",
      gave: "растения стали размножаться без свободной воды и лучше переживать сушу",
    },
    {
      id: "complete-metamorphosis",
      title: "полное превращение",
      image: "assets/photos/local-butterfly.jpg",
      timeMa: 350,
      eraId: "paleozoic",
      periodId: "carboniferous",
      novelty: "личинка и взрослое насекомое живут по-разному",
      gave: "дети и взрослые меньше конкурируют друг с другом и могут занимать разные ниши",
    },
    {
      id: "amniotic-egg",
      title: "амниотическое яйцо",
      image: "assets/photos/lizard-eggs.jpg",
      timeMa: 320,
      eraId: "paleozoic",
      periodId: "carboniferous",
      novelty: "зародыш развивается в защитных оболочках",
      gave: "размножение стало меньше зависеть от воды",
    },
    {
      id: "synapsid-skull",
      title: "синапсидное окно",
      image: "assets/photos/dimetrodon.png",
      timeMa: 315,
      eraId: "paleozoic",
      periodId: "carboniferous",
      novelty: "одно височное окно за глазом",
      gave: "челюстные мышцы получили новые места крепления, а наша линия пошла к млекопитающим",
    },
    {
      id: "diapsid-skull",
      title: "диапсидные окна",
      image: "assets/photos/komodo.jpg",
      timeMa: 295,
      eraId: "paleozoic",
      periodId: "permian",
      novelty: "два височных окна за глазом",
      gave: "череп стал легче и удобнее для сильных челюстных мышц",
    },
    {
      id: "archosaurs",
      title: "архозавры",
      image: "assets/photos/alligator.jpg",
      timeMa: 250,
      eraId: "mesozoic",
      periodId: "triassic",
      novelty: "более активная стойка и движение",
      gave: "эта линия дала крокодилов, птерозавров, динозавров и птиц",
    },
    {
      id: "dinosaurs",
      title: "динозавры",
      image: "assets/photos/herrerasaurus.jpg",
      timeMa: 235,
      eraId: "mesozoic",
      periodId: "triassic",
      novelty: "ноги стоят под телом",
      gave: "ходьба стала мощной и экономной, а динозавры заняли множество наземных ролей",
    },
    {
      id: "pterosaur-flight",
      title: "полет птерозавров",
      image: "assets/photos/pteranodon.png",
      timeMa: 228,
      eraId: "mesozoic",
      periodId: "triassic",
      novelty: "крыло из кожи на удлиненном пальце",
      gave: "позвоночные впервые стали активными летунами",
    },
    {
      id: "mammals",
      title: "млекопитающие",
      image: "assets/photos/morganucodon.jpg",
      timeMa: 220,
      eraId: "mesozoic",
      periodId: "triassic",
      novelty: "шерсть, молоко и более теплое тело",
      gave: "детенышей стало проще кормить и защищать",
    },
    {
      id: "theropod-feathers",
      title: "перья у теропод",
      image: "assets/photos/velociraptor.jpg",
      timeMa: 170,
      eraId: "mesozoic",
      periodId: "jurassic",
      novelty: "покров из перьев",
      gave: "перья помогали сохранять тепло, показывать себя и позже стали частью крыла",
    },
    {
      id: "placentals",
      title: "плацентарные",
      image: "assets/photos/squirrel.jpg",
      timeMa: 160,
      eraId: "mesozoic",
      periodId: "jurassic",
      novelty: "долгое питание детеныша через плаценту",
      gave: "детеныш мог дольше развиваться внутри тела матери",
    },
    {
      id: "birds",
      title: "птицы",
      image: "assets/photos/archaeopteryx.jpg",
      timeMa: 150,
      eraId: "mesozoic",
      periodId: "jurassic",
      novelty: "перья и крылья в птичьей линии динозавров",
      gave: "полет и теплоизоляция открыли новую жизнь в воздухе",
    },
    {
      id: "flowers",
      title: "цветковые растения",
      image: "assets/photos/plant-magnolia.jpg",
      timeMa: 140,
      eraId: "mesozoic",
      periodId: "cretaceous",
      novelty: "цветок и плод",
      gave: "семена стали лучше распространяться, часто с помощью животных",
    },
    {
      id: "modern-birds",
      title: "современные птицы",
      image: "assets/photos/sparrow.jpg",
      timeMa: 100,
      eraId: "mesozoic",
      periodId: "cretaceous",
      novelty: "клюв, короткий хвост и легкое тело",
      gave: "птицы стали разнообразными летающими, плавающими и бегающими динозаврами",
    },
    {
      id: "social-insects",
      title: "общественные насекомые",
      image: "assets/photos/local-ant.jpg",
      timeMa: 100,
      eraId: "mesozoic",
      periodId: "cretaceous",
      novelty: "семьи с разделением работы",
      gave: "колония стала работать как большой организм: строить, искать пищу и защищаться вместе",
    },
    {
      id: "grasses",
      title: "злаки",
      image: "assets/photos/plant-grass.jpg",
      timeMa: 70,
      eraId: "mesozoic",
      periodId: "cretaceous",
      novelty: "травянистый рост и зерна",
      gave: "позже злаки создали огромные травяные пространства и стали важной пищей для людей",
    },
    {
      id: "bat-flight",
      title: "полет летучих мышей",
      image: "assets/photos/bat.jpg",
      timeMa: 55,
      eraId: "cenozoic",
      periodId: "paleogene",
      novelty: "крыло из кожи между пальцами",
      gave: "млекопитающие заняли ночной воздух и научились охотиться в полете",
    },
    {
      id: "primates",
      title: "приматы",
      image: "assets/photos/lemur.jpg",
      timeMa: 55,
      eraId: "cenozoic",
      periodId: "paleogene",
      novelty: "цепкие руки и хорошее зрение",
      gave: "жизнь на ветках стала удобнее: хвататься, видеть расстояние и учиться движениям",
    },
    {
      id: "whales",
      title: "киты уходят в море",
      image: "assets/photos/humpback-whale.jpg",
      timeMa: 50,
      eraId: "cenozoic",
      periodId: "paleogene",
      novelty: "млекопитающие снова становятся водными",
      gave: "дыхание воздухом, теплокровность и живорождение заработали в океане",
    },
    {
      id: "apes",
      title: "человекообразные",
      image: "assets/photos/orangutan.jpg",
      timeMa: 20,
      eraId: "cenozoic",
      periodId: "neogene",
      novelty: "нет хвоста, гибкие плечи и крупный мозг",
      gave: "руки стали особенно важны для лазания, хватания и обучения",
    },
    {
      id: "hominins",
      title: "прямохождение",
      image: "assets/photos/australopithecus.jpg",
      timeMa: 6,
      eraId: "cenozoic",
      periodId: "neogene",
      novelty: "ходьба на двух ногах",
      gave: "руки освободились, а обзор над травой стал лучше",
    },
    {
      id: "stone-tools",
      title: "каменные орудия",
      image: "assets/photos/log-stone-tool.jpg",
      timeMa: 3.3,
      eraId: "cenozoic",
      periodId: "neogene",
      novelty: "предметы специально меняют под задачу",
      gave: "руки, мозг и обучение начали сильнее менять поведение нашей линии",
    },
    {
      id: "controlled-fire",
      title: "управление огнем",
      image: "assets/photos/log-lascaux.jpg",
      timeMa: 1,
      eraId: "cenozoic",
      periodId: "quaternary",
      novelty: "огонь становится частью жизни людей",
      gave: "тепло, свет, защита и приготовление пищи изменили стоянки и общение",
    },
    {
      id: "homo-sapiens",
      title: "Homo sapiens",
      image: "assets/photos/human.jpg",
      timeMa: 0.3,
      eraId: "cenozoic",
      periodId: "quaternary",
      novelty: "наш вид появляется в Африке",
      gave: "биологическая эволюция соединяется с очень сильной культурной передачей",
    },
    {
      id: "symbolic-art",
      title: "символы и искусство",
      image: "assets/photos/log-lascaux.jpg",
      timeMa: 0.04,
      eraId: "cenozoic",
      periodId: "quaternary",
      novelty: "рисунки, украшения и знаки",
      gave: "память группы стала видимой и могла передаваться через предметы и изображения",
    },
    {
      id: "agriculture",
      title: "земледелие",
      image: "assets/photos/log-wheat.jpg",
      timeMa: 0.012,
      eraId: "cenozoic",
      periodId: "quaternary",
      novelty: "люди выращивают растения и меняют ландшафт",
      gave: "пища стала планироваться заранее, появились поселения, запасы и новые общества",
    },
  ],

  nodeLevels: [
    { node: "жизнь", level: "easy" },
    { node: "прокариоты", level: "easy" },
    { node: "эукариоты", level: "easy" },
    { node: "архепластиды", level: "easy" },
    { node: "зеленые растения", level: "easy" },
    { node: "грибы", level: "easy" },
    { node: "животные", level: "easy" },
    { node: "моллюски", level: "easy" },
    { node: "членистоногие", level: "easy" },
    { node: "насекомые", level: "easy" },
    { node: "хордовые", level: "easy" },
    { node: "костные позвоночные", level: "easy" },
    { node: "четвероногие", level: "easy" },
    { node: "амниоты", level: "easy" },
    { node: "синапсиды", level: "easy" },
    { node: "завропсиды", level: "easy" },
    { node: "млекопитающие", level: "easy" },
    { node: "динозавры", level: "easy" },
    { node: "птицы", level: "easy" },
    { node: "плацентарные", level: "easy" },
    { node: "приматы", level: "easy" },

    { node: "опистоконты", level: "medium" },
    { node: "стрептофиты", level: "medium" },
    { node: "наземные растения", level: "medium" },
    { node: "сосудистые растения", level: "medium" },
    { node: "семенные растения", level: "medium" },
    { node: "цветковые", level: "medium" },
    { node: "билатерии", level: "medium" },
    { node: "первичноротые", level: "medium" },
    { node: "вторичноротые", level: "medium" },
    { node: "черепные", level: "medium" },
    { node: "челюстноротые", level: "medium" },
    { node: "амфибии", level: "medium" },
    { node: "архозавры", level: "medium" },
    { node: "лепидозавры", level: "medium" },
    { node: "терапсиды", level: "medium" },
    { node: "звери", level: "medium" },
    { node: "сумчатые", level: "medium" },
    { node: "однопроходные", level: "medium" },
    { node: "грызуны", level: "medium" },
    { node: "обезьяны", level: "medium" },
    { node: "человекообразные", level: "medium" },
    { node: "псевдозухии", level: "medium" },
    { node: "птерозавры", level: "medium" },
    { node: "тероподы", level: "medium" },
    { node: "ящеротазовые", level: "medium" },
    { node: "птицетазовые", level: "medium" },
    { node: "хелицеровые", level: "medium" },
    { node: "шестиногие", level: "medium" },
    { node: "головоногие", level: "medium" },
    { node: "иглокожие", level: "medium" },

    { node: "красные водоросли", level: "hard" },
    { node: "зеленые водоросли", level: "hard" },
    { node: "хоанозои", level: "hard" },
    { node: "мхи", level: "hard" },
    { node: "папоротники", level: "hard" },
    { node: "хвощи", level: "hard" },
    { node: "голосеменные", level: "hard" },
    { node: "однодольные", level: "hard" },
    { node: "кишечнополостные", level: "hard" },
    { node: "кольчатые черви", level: "hard" },
    { node: "брюхоногие", level: "hard" },
    { node: "плоские черви", level: "hard" },
    { node: "линяющие", level: "hard" },
    { node: "панартроподы", level: "hard" },
    { node: "перепончатокрылые", level: "hard" },
    { node: "двукрылые", level: "hard" },
    { node: "чешуекрылые", level: "hard" },
    { node: "крылатые насекомые", level: "hard" },
    { node: "прямокрылые", level: "hard" },
    { node: "жуки", level: "hard" },
    { node: "бескрылые насекомые", level: "hard" },
    { node: "ракообразные", level: "hard" },
    { node: "бесчерепные", level: "hard" },
    { node: "бесчелюстные", level: "hard" },
    { node: "хрящевые рыбы", level: "hard" },
    { node: "панцирные рыбы", level: "hard" },
    { node: "лучеперые", level: "hard" },
    { node: "лопастеперые", level: "hard" },
    { node: "тетраподоморфы", level: "hard" },
    { node: "хвостатые амфибии", level: "hard" },
    { node: "ранние завропсиды", level: "hard" },
    { node: "чешуйчатые", level: "hard" },
    { node: "крокодилы", level: "hard" },
    { node: "равизухии", level: "hard" },
    { node: "авеметатарзалии", level: "hard" },
    { node: "ранние динозавры", level: "hard" },
    { node: "завроподоморфы", level: "hard" },
    { node: "завроподы", level: "hard" },
    { node: "цератопсы", level: "hard" },
    { node: "карнозавры", level: "hard" },
    { node: "целурозавры", level: "hard" },
    { node: "тираннозавроиды", level: "hard" },
    { node: "дромеозавры", level: "hard" },
    { node: "авиалы", level: "hard" },
    { node: "ранние птицы", level: "hard" },
    { node: "воробьинообразные", level: "hard" },
    { node: "врановые", level: "hard" },
    { node: "сфенакодонты", level: "hard" },
    { node: "цинодонты", level: "hard" },
    { node: "млекопитающие формы", level: "hard" },
    { node: "двурезцовые сумчатые", level: "hard" },
    { node: "зайцеобразные", level: "hard" },
    { node: "землекоповые", level: "hard" },
    { node: "афротерии", level: "hard" },
    { node: "хоботные", level: "hard" },
    { node: "лавразиотерии", level: "hard" },
    { node: "китопарнокопытные", level: "hard" },
    { node: "китообразные", level: "hard" },
    { node: "рукокрылые", level: "hard" },
    { node: "полуобезьяны", level: "hard" },
    { node: "узконосые обезьяны", level: "hard" }
  ],

  cards: {
    bacteria: {
      name: "Бактерия",
      image: "assets/photos/bacteria.jpg",
      note: "прокариоты",
      level: "easy",
      path: ["жизнь", "прокариоты", "бактерии"],
    },
    amoeba: {
      name: "Амеба",
      image: "assets/photos/amoeba.jpg",
      note: "эукариоты",
      level: "easy",
      path: ["жизнь", "эукариоты", "амебы"],
    },
    mushroom: {
      name: "Гриб",
      image: "assets/photos/mushroom.jpg",
      note: "грибы",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "грибы"],
    },
    choanoflagellate: {
      name: "Хоанофлагеллят",
      image: "assets/photos/choanoflagellate.jpg",
      note: "родня животных",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "хоанозои", "хоанофлагелляты"],
    },
    oak: {
      name: "Дуб",
      image: "assets/photos/plant-oak.jpg",
      note: "растения",
      level: "easy",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "сосудистые растения", "семенные растения", "цветковые", "дубы"],
    },
    moss: {
      name: "Мох",
      image: "assets/photos/plant-moss.jpg",
      note: "наземные растения",
      level: "medium",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "мхи"],
    },
    pine: {
      name: "Сосна",
      image: "assets/photos/plant-pine-cone.jpg",
      note: "семенные растения",
      level: "medium",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "сосудистые растения", "семенные растения", "голосеменные", "сосны"],
    },
    greenAlgae: {
      name: "Зеленая водоросль",
      image: "assets/photos/plant-green-algae.jpg",
      note: "зеленые растения",
      level: "medium",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "зеленые водоросли"],
    },
    redAlgae: {
      name: "Красная водоросль",
      image: "assets/photos/plant-red-algae.jpg",
      note: "архепластиды",
      level: "hard",
      path: ["жизнь", "эукариоты", "архепластиды", "красные водоросли"],
    },
    fern: {
      name: "Папоротник",
      image: "assets/photos/plant-fern.jpg",
      note: "сосудистые растения",
      level: "medium",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "сосудистые растения", "папоротники"],
    },
    horsetail: {
      name: "Хвощ",
      image: "assets/photos/plant-horsetail.jpg",
      note: "сосудистые растения",
      level: "hard",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "сосудистые растения", "хвощи"],
    },
    grass: {
      name: "Злак",
      image: "assets/photos/plant-grass.jpg",
      note: "цветковые",
      level: "medium",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "сосудистые растения", "семенные растения", "цветковые", "однодольные", "злаки"],
    },
    magnolia: {
      name: "Магнолия",
      image: "assets/photos/plant-magnolia.jpg",
      note: "цветковые",
      level: "hard",
      path: ["жизнь", "эукариоты", "архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "сосудистые растения", "семенные растения", "цветковые", "магнолии"],
    },
    sponge: {
      name: "Губка",
      image: "assets/photos/sponge.jpg",
      note: "животные без билатерии",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "губки"],
    },
    jellyfish: {
      name: "Медуза",
      image: "assets/photos/jellyfish.jpg",
      note: "радиальная симметрия",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "кишечнополостные", "медузы"],
    },
    earthworm: {
      name: "Дождевой червь",
      image: "assets/photos/local-earthworm.jpg",
      note: "первичноротые",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "кольчатые черви", "дождевые черви"],
    },
    slug: {
      name: "Слизень",
      image: "assets/photos/local-slug.jpg",
      note: "моллюски",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "моллюски", "брюхоногие", "слизни"],
    },
    planarian: {
      name: "Планария",
      image: "assets/photos/planarian.jpg",
      note: "плоские черви",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "плоские черви", "планарии"],
    },
    octopus: {
      name: "Осьминог",
      image: "assets/photos/octopus.jpg",
      note: "головоногие",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "моллюски", "головоногие", "осьминоги"],
    },
    nautilus: {
      name: "Наутилус",
      image: "assets/photos/nautilus.jpg",
      note: "головоногие",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "моллюски", "головоногие", "наутилусы"],
    },
    tardigrade: {
      name: "Тихоходка",
      image: "assets/photos/tardigrade.jpg",
      note: "панартроподы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "тихоходки"],
    },
    bee: {
      name: "Пчела",
      image: "assets/photos/local-bee.jpg",
      note: "насекомые",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "перепончатокрылые", "пчелы"],
    },
    ant: {
      name: "Муравей",
      image: "assets/photos/local-ant.jpg",
      note: "перепончатокрылые",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "перепончатокрылые", "муравьи"],
    },
    butterfly: {
      name: "Бабочка",
      image: "assets/photos/local-butterfly.jpg",
      note: "чешуекрылые",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "чешуекрылые", "бабочки"],
    },
    mosquito: {
      name: "Комар",
      image: "assets/photos/local-mosquito.jpg",
      note: "двукрылые",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "двукрылые", "комары"],
    },
    dragonfly: {
      name: "Стрекоза",
      image: "assets/photos/arthropod-dragonfly.jpg",
      note: "крылатые насекомые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "крылатые насекомые", "стрекозы"],
    },
    grasshopper: {
      name: "Кузнечик",
      image: "assets/photos/arthropod-grasshopper.jpg",
      note: "прямокрылые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "прямокрылые", "кузнечики"],
    },
    ladybird: {
      name: "Божья коровка",
      image: "assets/photos/arthropod-ladybird.jpg",
      note: "жуки",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "жуки", "божьи коровки"],
    },
    wasp: {
      name: "Оса",
      image: "assets/photos/arthropod-wasp.jpg",
      note: "перепончатокрылые",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "перепончатокрылые", "осы"],
    },
    fly: {
      name: "Муха",
      image: "assets/photos/arthropod-fly.jpg",
      note: "двукрылые",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "двукрылые", "мухи"],
    },
    springtail: {
      name: "Ногохвостка",
      image: "assets/photos/arthropod-springtail.jpg",
      note: "шестиногие",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "ногохвостки"],
    },
    silverfish: {
      name: "Чешуйница",
      image: "assets/photos/arthropod-silverfish.jpg",
      note: "бескрылые насекомые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "шестиногие", "насекомые", "бескрылые насекомые", "чешуйницы"],
    },
    spider: {
      name: "Паук",
      image: "assets/photos/local-spider.jpg",
      note: "хелицеровые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "хелицеровые", "пауки"],
    },
    horseshoeCrab: {
      name: "Мечехвост",
      image: "assets/photos/horseshoe-crab.jpg",
      note: "хелицеровые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "хелицеровые", "мечехвосты"],
    },
    crayfish: {
      name: "Рак",
      image: "assets/photos/local-crayfish.jpg",
      note: "ракообразные",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "первичноротые", "линяющие", "панартроподы", "членистоногие", "ракообразные", "раки"],
    },
    starfish: {
      name: "Морская звезда",
      image: "assets/photos/starfish.jpg",
      note: "иглокожие",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "иглокожие", "морские звезды"],
    },
    seaUrchin: {
      name: "Морской еж",
      image: "assets/photos/sea-urchin.jpg",
      note: "иглокожие",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "иглокожие", "морские ежи"],
    },
    lancelet: {
      name: "Ланцетник",
      image: "assets/photos/lancelet.jpg",
      note: "бесчерепные хордовые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "бесчерепные", "ланцетники"],
    },
    lamprey: {
      name: "Минога",
      image: "assets/photos/lamprey.jpg",
      note: "бесчелюстные",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "бесчелюстные", "миноги"],
    },
    shark: {
      name: "Акула",
      image: "assets/photos/shark.jpg",
      note: "хрящевые рыбы",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "хрящевые рыбы", "акулы"],
    },
    dunkleosteus: {
      name: "Дунклеостей",
      image: "assets/photos/dunkleosteus-jaw.jpg",
      note: "панцирная рыба",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "панцирные рыбы", "дунклеостей"],
    },
    perch: {
      name: "Окунь",
      image: "assets/photos/local-perch.jpg",
      note: "костные рыбы",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лучеперые", "окуни"],
    },
    coelacanth: {
      name: "Латимерия",
      image: "assets/photos/coelacanth.jpg",
      note: "лопастеперые рыбы",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "латимерии"],
    },
    lungfish: {
      name: "Двоякодышащая рыба",
      image: "assets/photos/lungfish.jpg",
      note: "родня четвероногих",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "двоякодышащие рыбы"],
    },
    tiktaalik: {
      name: "Тиктаалик",
      image: "assets/photos/tiktaalik.jpg",
      note: "переход к четвероногим",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "тетраподоморфы", "тиктаалик"],
    },
    frog: {
      name: "Лягушка",
      image: "assets/photos/frog.jpg",
      note: "амфибии",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амфибии", "лягушки"],
    },
    axolotl: {
      name: "Аксолотль",
      image: "assets/photos/axolotl.jpg",
      note: "хвостатые амфибии",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амфибии", "хвостатые амфибии", "аксолотли"],
    },
    captorhinus: {
      name: "Капторин",
      image: "assets/photos/captorhinus.jpg",
      note: "ранний завропсид",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "ранние завропсиды", "капторины"],
    },
    crocodile: {
      name: "Крокодил",
      image: "assets/photos/crocodile.jpg",
      note: "архозавры",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "псевдозухии", "крокодилы"],
    },
    alligator: {
      name: "Аллигатор",
      image: "assets/photos/alligator.jpg",
      note: "крокодилы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "псевдозухии", "крокодилы", "аллигаторы"],
    },
    prestosuchus: {
      name: "Престозух",
      image: "assets/photos/prestosuchus.png",
      note: "псевдозухии",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "псевдозухии", "равизухии", "престозухи"],
    },
    pteranodon: {
      name: "Птеранодон",
      image: "assets/photos/pteranodon.png",
      note: "птерозавры",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "птерозавры", "птеранодоны"],
    },
    tuatara: {
      name: "Гаттерия",
      image: "assets/photos/tuatara.jpg",
      note: "лепидозавры",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "лепидозавры", "гаттерии"],
    },
    lizard: {
      name: "Ящерица",
      image: "assets/photos/komodo.jpg",
      note: "лепидозавры",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "лепидозавры", "чешуйчатые", "ящерицы"],
    },
    snake: {
      name: "Змея",
      image: "assets/photos/snake.jpg",
      note: "чешуйчатые",
      level: "medium",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "лепидозавры", "чешуйчатые", "змеи"],
    },
    sparrow: {
      name: "Воробей",
      image: "assets/photos/sparrow.jpg",
      note: "птицы",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "динозавры", "тероподы", "птицы"],
    },
    raven: {
      name: "Ворон",
      image: "assets/photos/raven.jpg",
      note: "врановые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "динозавры", "тероподы", "птицы", "воробьинообразные", "врановые", "вороны"],
    },
    herrerasaurus: {
      name: "Герреразавр",
      image: "assets/photos/herrerasaurus.jpg",
      note: "ранние динозавры",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "динозавры", "ранние динозавры", "герреразавры"],
    },
    triceratops: {
      name: "Трицератопс",
      image: "assets/photos/triceratops.jpg",
      note: "птицетазовые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "динозавры", "птицетазовые", "цератопсы", "трицератопсы"],
    },
    apatosaurus: {
      name: "Апатозавр",
      image: "assets/photos/apatosaurus.png",
      note: "завроподы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "динозавры", "ящеротазовые", "завроподоморфы", "завроподы", "апатозавры"],
    },
    allosaurus: {
      name: "Аллозавр",
      image: "assets/photos/allosaurus.jpg",
      note: "тероподы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "динозавры", "ящеротазовые", "тероподы", "карнозавры", "аллозавры"],
    },
    tyrannosaurus: {
      name: "Тираннозавр",
      image: "assets/photos/tyrannosaurus.jpg",
      note: "тероподы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "динозавры", "ящеротазовые", "тероподы", "целурозавры", "тираннозавроиды", "тираннозавры"],
    },
    velociraptor: {
      name: "Велоцираптор",
      image: "assets/photos/velociraptor.jpg",
      note: "дромеозавры",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "динозавры", "ящеротазовые", "тероподы", "целурозавры", "дромеозавры", "велоцирапторы"],
    },
    archaeopteryx: {
      name: "Археоптерикс",
      image: "assets/photos/archaeopteryx.jpg",
      note: "ранние птицы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "завропсиды", "архозавры", "авеметатарзалии", "динозавры", "ящеротазовые", "тероподы", "целурозавры", "авиалы", "ранние птицы", "археоптериксы"],
    },
    mouse: {
      name: "Мышь",
      image: "assets/photos/mouse.jpg",
      note: "млекопитающие",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "грызуны", "мыши"],
    },
    kangaroo: {
      name: "Кенгуру",
      image: "assets/photos/kangaroo.jpg",
      note: "сумчатые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "сумчатые", "кенгуру"],
    },
    koala: {
      name: "Коала",
      image: "assets/photos/koala.jpg",
      note: "сумчатые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "сумчатые", "двурезцовые сумчатые", "коалы"],
    },
    platypus: {
      name: "Утконос",
      image: "assets/photos/monotreme.jpg",
      note: "однопроходные",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "однопроходные", "утконосы"],
    },
    echidna: {
      name: "Ехидна",
      image: "assets/photos/echidna.jpg",
      note: "однопроходные",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "однопроходные", "ехидны"],
    },
    dimetrodon: {
      name: "Диметродон",
      image: "assets/photos/dimetrodon.png",
      note: "ранний синапсид",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "сфенакодонты", "диметродоны"],
    },
    gorgonops: {
      name: "Горгонопс",
      image: "assets/photos/gorgonops.png",
      note: "терапсиды",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "терапсиды", "горгонопсы"],
    },
    thrinaxodon: {
      name: "Тринаксодон",
      image: "assets/photos/thrinaxodon.jpg",
      note: "цинодонты",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "терапсиды", "цинодонты", "тринаксодоны"],
    },
    morganucodon: {
      name: "Морганукодон",
      image: "assets/photos/morganucodon.jpg",
      note: "млекопитающие формы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "терапсиды", "цинодонты", "млекопитающие формы", "морганукодоны"],
    },
    rabbit: {
      name: "Кролик",
      image: "assets/photos/rabbit.jpg",
      note: "плацентарные",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "зайцеобразные", "кролики"],
    },
    nakedMoleRat: {
      name: "Голый землекоп",
      image: "assets/photos/naked-mole-rat.jpg",
      note: "грызуны",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "грызуны", "землекоповые", "голые землекопы"],
    },
    elephant: {
      name: "Слон",
      image: "assets/photos/elephant.jpg",
      note: "афротерии",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "афротерии", "хоботные", "слоны"],
    },
    whale: {
      name: "Кит",
      image: "assets/photos/humpback-whale.jpg",
      note: "китообразные",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "лавразиотерии", "китопарнокопытные", "китообразные", "киты"],
    },
    bat: {
      name: "Летучая мышь",
      image: "assets/photos/bat.jpg",
      note: "рукокрылые",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "лавразиотерии", "рукокрылые", "летучие мыши"],
    },
    squirrel: {
      name: "Белка",
      image: "assets/photos/squirrel.jpg",
      note: "грызуны",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "грызуны", "белки"],
    },
    lemur: {
      name: "Лемур",
      image: "assets/photos/lemur.jpg",
      note: "приматы",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "приматы", "полуобезьяны", "лемуры"],
    },
    macaque: {
      name: "Макака",
      image: "assets/photos/macaque.jpg",
      note: "обезьяны",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "приматы", "обезьяны", "узконосые обезьяны", "макаки"],
    },
    baboon: {
      name: "Павиан",
      image: "assets/photos/baboon.jpg",
      note: "узконосые обезьяны",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "приматы", "обезьяны", "узконосые обезьяны", "павианы"],
    },
    orangutan: {
      name: "Орангутан",
      image: "assets/photos/orangutan.jpg",
      note: "человекообразные",
      level: "hard",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "приматы", "обезьяны", "человекообразные", "орангутаны"],
    },
    chimpanzee: {
      name: "Шимпанзе",
      image: "assets/photos/chimpanzee.jpg",
      note: "человекообразные",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "приматы", "обезьяны", "человекообразные", "шимпанзе"],
    },
    human: {
      name: "Человек",
      image: "assets/photos/human.jpg",
      note: "люди",
      level: "easy",
      path: ["жизнь", "эукариоты", "опистоконты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "звери", "плацентарные", "приматы", "обезьяны", "человекообразные", "люди"],
    },
  },

  modes: [
    {
      id: "closer",
      title: "Кто ближе к человеку?",
      hint: "Выбери того, чей последний общий предок с человеком жил позже.",
    },
    {
      id: "ancestor",
      title: "Последний общий предок",
      hint: "Выбери самую близкую общую группу для двух существ.",
    },
    {
      id: "chain",
      title: "Собери цепочку",
      hint: "Нажимай карточки от древней общей ветки к более близкой.",
    },
    {
      id: "branches",
      title: "Собери две ветки",
      hint: "Разложи узлы по двум веткам после общего предка.",
    },
    {
      id: "timeline",
      title: "Когда появилось?",
      hint: "Сначала выбери большой отрезок времени, потом уточни период.",
    },
  ],
};
