window.EVOL_GAMES = {
  levels: [
    { id: "easy", title: "легкий" },
    { id: "medium", title: "средний" },
    { id: "hard", title: "сложный" },
  ],

  cards: {
    bacteria: { name: "Бактерия", image: "assets/photos/bacteria.jpg", note: "прокариоты" },
    amoeba: { name: "Амеба", image: "assets/photos/amoeba.jpg", note: "эукариоты" },
    mushroom: { name: "Гриб", image: "assets/photos/mushroom.jpg", note: "грибы" },
    oak: { name: "Дуб", image: "assets/photos/plant-oak.jpg", note: "растения" },
    moss: { name: "Мох", image: "assets/photos/plant-moss.jpg", note: "наземные растения" },
    pine: { name: "Сосна", image: "assets/photos/plant-pine-cone.jpg", note: "семенные растения" },
    sponge: { name: "Губка", image: "assets/photos/sponge.jpg", note: "животные без билатерии" },
    jellyfish: { name: "Медуза", image: "assets/photos/jellyfish.jpg", note: "радиальная симметрия" },
    earthworm: { name: "Дождевой червь", image: "assets/photos/local-earthworm.jpg", note: "первичноротые" },
    slug: { name: "Слизень", image: "assets/photos/local-slug.jpg", note: "моллюски" },
    bee: { name: "Пчела", image: "assets/photos/local-bee.jpg", note: "насекомые" },
    spider: { name: "Паук", image: "assets/photos/local-spider.jpg", note: "хелицеровые" },
    crayfish: { name: "Рак", image: "assets/photos/local-crayfish.jpg", note: "ракообразные" },
    lamprey: { name: "Минога", image: "assets/photos/lamprey.jpg", note: "бесчелюстные" },
    shark: { name: "Акула", image: "assets/photos/shark.jpg", note: "хрящевые рыбы" },
    perch: { name: "Окунь", image: "assets/photos/local-perch.jpg", note: "костные рыбы" },
    coelacanth: { name: "Латимерия", image: "assets/photos/coelacanth.jpg", note: "лопастеперые рыбы" },
    lungfish: { name: "Двоякодышащая рыба", image: "assets/photos/lungfish.jpg", note: "родня четвероногих" },
    frog: { name: "Лягушка", image: "assets/photos/frog.jpg", note: "амфибии" },
    crocodile: { name: "Крокодил", image: "assets/photos/crocodile.jpg", note: "архозавры" },
    lizard: { name: "Ящерица", image: "assets/photos/komodo.jpg", note: "лепидозавры" },
    snake: { name: "Змея", image: "assets/photos/snake.jpg", note: "чешуйчатые" },
    sparrow: { name: "Воробей", image: "assets/photos/sparrow.jpg", note: "птицы" },
    mouse: { name: "Мышь", image: "assets/photos/mouse.jpg", note: "млекопитающие" },
    kangaroo: { name: "Кенгуру", image: "assets/photos/kangaroo.jpg", note: "сумчатые" },
    chimpanzee: { name: "Шимпанзе", image: "assets/photos/chimpanzee.jpg", note: "человекообразные" },
    human: { name: "Человек", image: "assets/photos/human.jpg", note: "люди" },
  },

  modes: [
    {
      id: "closer",
      title: "Кто ближе к человеку?",
      hint: "Выбери того, чей последний общий предок с человеком жил позже.",
    },
    {
      id: "ancestor",
      title: "Последний общий предок",
      hint: "Выбери самую близкую общую группу для двух существ.",
    },
    {
      id: "chain",
      title: "Собери цепочку",
      hint: "Нажимай карточки от древней общей ветки к более близкой.",
    },
  ],

  questions: {
    closer: [
      {
        id: "closer-shark-sparrow",
        level: "easy",
        pair: ["shark", "sparrow"],
        answer: "sparrow",
        prompt: "Кто ближе к человеку?",
        explanation: "Птицы и люди оба амниоты; акулы отделились раньше, до костной линии позвоночных.",
      },
      {
        id: "closer-bee-frog",
        level: "easy",
        pair: ["bee", "frog"],
        answer: "frog",
        prompt: "Кто ближе к человеку?",
        explanation: "Лягушка, как и человек, позвоночное и четвероногое животное; насекомые ушли по другой ветке гораздо раньше.",
      },
      {
        id: "closer-crocodile-perch",
        level: "easy",
        pair: ["crocodile", "perch"],
        answer: "crocodile",
        prompt: "Кто ближе к человеку?",
        explanation: "Крокодил и человек оба амниоты. Окунь отделился раньше, на рыбной ветке.",
      },
      {
        id: "closer-mushroom-oak",
        level: "easy",
        pair: ["mushroom", "oak"],
        answer: "mushroom",
        prompt: "Кто ближе к человеку?",
        explanation: "Грибы ближе к животным, чем растения: животные и грибы входят в опистоконтов.",
      },
      {
        id: "closer-mouse-frog",
        level: "easy",
        pair: ["mouse", "frog"],
        answer: "mouse",
        prompt: "Кто ближе к человеку?",
        explanation: "Мышь и человек оба млекопитающие; лягушки отделились до амниот.",
      },
      {
        id: "closer-bacteria-amoeba",
        level: "easy",
        pair: ["bacteria", "amoeba"],
        answer: "amoeba",
        prompt: "Кто ближе к человеку?",
        explanation: "Амеба, как и человек, эукариот: у них есть клеточное ядро. Бактерии отделились гораздо раньше.",
      },
      {
        id: "closer-sponge-earthworm",
        level: "medium",
        pair: ["sponge", "earthworm"],
        answer: "earthworm",
        prompt: "Кто ближе к человеку?",
        explanation: "Дождевой червь и человек оба билатерии; губки отделились раньше, до нервной системы и двустороннего тела.",
      },
      {
        id: "closer-jellyfish-slug",
        level: "medium",
        pair: ["jellyfish", "slug"],
        answer: "slug",
        prompt: "Кто ближе к человеку?",
        explanation: "Слизень относится к билатериям, как и человек. Медузы отделились раньше, на радиально-симметричной ветке.",
      },
      {
        id: "closer-lamprey-shark",
        level: "medium",
        pair: ["lamprey", "shark"],
        answer: "shark",
        prompt: "Кто ближе к человеку?",
        explanation: "Акула уже челюстноротое позвоночное. Миноги остались на более ранней бесчелюстной ветке.",
      },
      {
        id: "closer-shark-perch",
        level: "medium",
        pair: ["shark", "perch"],
        answer: "perch",
        prompt: "Кто ближе к человеку?",
        explanation: "Окунь костная рыба; наша линия идет через костных позвоночных. Акулы отделились на хрящевой ветке.",
      },
      {
        id: "closer-coelacanth-perch",
        level: "medium",
        pair: ["coelacanth", "perch"],
        answer: "coelacanth",
        prompt: "Кто ближе к человеку?",
        explanation: "Латимерия лопастеперая рыба; четвероногие вышли из этой большой ветки, а лучеперые рыбы отделились раньше.",
      },
      {
        id: "closer-lungfish-frog",
        level: "hard",
        pair: ["lungfish", "frog"],
        answer: "frog",
        prompt: "Кто ближе к человеку?",
        explanation: "Лягушка уже четвероногое животное. Двоякодышащие рыбы близки к выходу на сушу, но остались водной веткой.",
      },
      {
        id: "closer-lizard-crocodile",
        level: "hard",
        pair: ["lizard", "crocodile"],
        answer: "crocodile",
        prompt: "Кто ближе к человеку?",
        explanation: "Обе ветки завропсидовые и не наша линия, но крокодилы и птицы находятся в архозаврах; это более поздняя развилка внутри амниот.",
      },
      {
        id: "closer-kangaroo-mouse",
        level: "hard",
        pair: ["kangaroo", "mouse"],
        answer: "mouse",
        prompt: "Кто ближе к человеку?",
        explanation: "Мышь и человек оба плацентарные млекопитающие; кенгуру относится к сумчатым.",
      },
      {
        id: "closer-chimpanzee-kangaroo",
        level: "easy",
        pair: ["chimpanzee", "kangaroo"],
        answer: "chimpanzee",
        prompt: "Кто ближе к человеку?",
        explanation: "Шимпанзе и человек оба человекообразные обезьяны; кенгуру отделился намного раньше, на ветке сумчатых.",
      },
    ],

    ancestor: [
      {
        id: "ancestor-human-frog",
        level: "easy",
        pair: ["human", "frog"],
        prompt: "Где последний общий предок?",
        options: ["эукариоты", "животные", "хордовые", "четвероногие", "амниоты"],
        answer: "четвероногие",
        explanation: "Человек и лягушка оба четвероногие, но лягушки не амниоты.",
      },
      {
        id: "ancestor-sparrow-crocodile",
        level: "easy",
        pair: ["sparrow", "crocodile"],
        prompt: "Где последний общий предок?",
        options: ["челюстноротые", "амниоты", "архозавры", "млекопитающие"],
        answer: "архозавры",
        explanation: "Птицы и крокодилы находятся внутри архозавровой ветки.",
      },
      {
        id: "ancestor-bee-human",
        level: "easy",
        pair: ["bee", "human"],
        prompt: "Где последний общий предок?",
        options: ["эукариоты", "животные", "билатерии", "хордовые"],
        answer: "билатерии",
        explanation: "Насекомые и люди оба билатеральные животные, но насекомые не хордовые.",
      },
      {
        id: "ancestor-oak-mushroom",
        level: "easy",
        pair: ["oak", "mushroom"],
        prompt: "Где последний общий предок?",
        options: ["эукариоты", "животные", "амниоты", "цветковые"],
        answer: "эукариоты",
        explanation: "Растения и грибы расходятся среди эукариот; животными грибы не являются.",
      },
      {
        id: "ancestor-jellyfish-human",
        level: "medium",
        pair: ["jellyfish", "human"],
        prompt: "Где последний общий предок?",
        options: ["животные", "билатерии", "хордовые", "амниоты"],
        answer: "животные",
        explanation: "Медуза и человек оба животные, но медузы не билатерии.",
      },
      {
        id: "ancestor-slug-bee",
        level: "medium",
        pair: ["slug", "bee"],
        prompt: "Где последний общий предок?",
        options: ["животные", "билатерии", "первичноротые", "членистоногие"],
        answer: "первичноротые",
        explanation: "Слизни и пчелы оба первичноротые; дальше их ветки расходятся на моллюсков и членистоногих.",
      },
      {
        id: "ancestor-shark-human",
        level: "medium",
        pair: ["shark", "human"],
        prompt: "Где последний общий предок?",
        options: ["хордовые", "черепные", "челюстноротые", "костные позвоночные"],
        answer: "челюстноротые",
        explanation: "Акула и человек оба челюстноротые; акулы не входят в костную ветку позвоночных.",
      },
      {
        id: "ancestor-lungfish-human",
        level: "hard",
        pair: ["lungfish", "human"],
        prompt: "Где последний общий предок?",
        options: ["костные позвоночные", "лопастеперые", "четвероногие", "амниоты"],
        answer: "лопастеперые",
        explanation: "Двоякодышащие рыбы и четвероногие находятся внутри лопастеперой ветки.",
      },
      {
        id: "ancestor-spider-crayfish",
        level: "hard",
        pair: ["spider", "crayfish"],
        prompt: "Где последний общий предок?",
        options: ["билатерии", "первичноротые", "членистоногие", "насекомые"],
        answer: "членистоногие",
        explanation: "Пауки и раки оба членистоногие, но не насекомые.",
      },
      {
        id: "ancestor-mouse-kangaroo",
        level: "hard",
        pair: ["mouse", "kangaroo"],
        prompt: "Где последний общий предок?",
        options: ["амниоты", "синапсиды", "млекопитающие", "плацентарные"],
        answer: "млекопитающие",
        explanation: "Мышь и кенгуру оба млекопитающие; плацентарной веткой является мышь, а кенгуру сумчатый.",
      },
    ],

    chain: [
      {
        id: "chain-human-short",
        level: "easy",
        prompt: "Собери путь к человеку",
        items: ["эукариоты", "животные", "билатерии", "хордовые", "четвероногие", "амниоты", "млекопитающие", "люди"],
        explanation: "Это укороченная цепочка: от клетки с ядром к нашей ветке.",
      },
      {
        id: "chain-birds",
        level: "easy",
        prompt: "Собери путь к птицам",
        items: ["эукариоты", "животные", "хордовые", "четвероногие", "амниоты", "завропсиды", "архозавры", "динозавры", "птицы"],
        explanation: "Птицы - живая ветка динозавров внутри архозавров.",
      },
      {
        id: "chain-plants",
        level: "medium",
        prompt: "Собери путь растений",
        items: ["архепластиды", "зеленые растения", "стрептофиты", "наземные растения", "сосудистые растения", "семенные растения", "цветковые"],
        explanation: "Это путь от фотосинтетической эукариотической линии к цветковым растениям.",
      },
      {
        id: "chain-arthropods",
        level: "medium",
        prompt: "Собери путь к насекомым",
        items: ["эукариоты", "животные", "билатерии", "первичноротые", "членистоногие", "шестиногие", "насекомые"],
        explanation: "Насекомые - ветка членистоногих внутри первичноротых животных.",
      },
      {
        id: "chain-human-long",
        level: "hard",
        prompt: "Собери длинный путь к человеку",
        items: ["эукариоты", "животные", "билатерии", "вторичноротые", "хордовые", "черепные", "челюстноротые", "костные позвоночные", "лопастеперые", "четвероногие", "амниоты", "синапсиды", "млекопитающие", "приматы", "человекообразные", "люди"],
        explanation: "Это длинная версия нашей линии от животных до людей.",
      },
    ],
  },
};
